### ISSUE TITLE
Permission issue  with CSB

### ISSUE THREAD

**Issue by robertreny** [ShawnTylerSchwartz/eeb-c177-w20#11]
Hi All,

I am having an issue pushing inside of the CSB repo. I removed and re-cloned the repo and still get the same message: 

remote: Permission to CSB-book/CSB.git denied to robertreny.
fatal: unable to access 'https://github.com/CSB-book/CSB.git/': The requested URL returned error: 403

- Robert

**Comment by goharmihranian** [comment]
The same thing is happening to me. Not sure how to continue.

**Comment by shawntz** [comment]
Hi @robertreny @goharmihranian Thanks for pointing this out. This was a mistake in my instructions as you cannot push changes from someone else's repository that you do not own (as it would not make sense if people could go around editing people's code directly). I changed the instructions on the homework assignment page on the course website to exclude the `Then, do the git add-commit-push workflow` portion from `Part 1, Step 1`.

**Comment by robertreny** [comment]
Got it thanks @ShawnTylerSchwartz !
