### ISSUE TITLE
Lab Homework Pt2

### ISSUE THREAD

**Issue by goharmihranian** [ShawnTylerSchwartz/eeb-c177-w20#12]
I'm not sure what number 4 is asking. Is our regular expression supposed to include the phrase "struggle for existence" or are we supposed to put in a regular expression that matches that whole  sentence?

Thank you!

**Comment by shawntz** [comment]
Your regular expression should match the whole sentence that contains the phrase “struggle for existence”. Therefore, it should return one match which is a whole sentence start to finish @goharmihranian

**Comment by Deap-Bhandal** [comment]
I also had a question on that number. Do we need the question mark at the end of the sentence highlighted or not?

**Comment by shawntz** [comment]
@Deap-Bhandal No you **don't** have to worry about capturing the question mark at the end of the sentence, just the text.
