### ISSUE TITLE
Lecture Homework Part 2

### ISSUE THREAD

**Issue by goharmihranian** [ShawnTylerSchwartz/eeb-c177-w20#13]
I am having trouble copying the first 25 lines from the Pacifici2013_data.csv file in the /Developer/repos/CSB/unix/data into the Pacifici-25lines.txt in my class-assignments/homework-two.

I have tried: 
head -n 25 Pacifici2013_data.csv ~/Developer/repos/eeb-c177-homework/class-assignments/homework-two/Pacifici-25lines.txt

I have also tried
head 25 Pacifici2013_data.csv | cp ~/Developer/repos/eeb-c177-homework/class-assignments/homework-two/Pacifici-25lines.txt

Please tell me what I'm doing wrong

**Comment by shawntz** [comment]
@goharmihranian there is a much simpler way to do this using the `>` symbol in your command.

Use `>` between the file name you want to copy from and the new file you'd like to inject the content into. Let me know if this works for you.

**Comment by goharmihranian** [comment]
@ShawnTylerSchwartz Yes, it worked, thank you! For some reason I was thinking that I had to do it all myself but I did that first step and then must moved it into the class-assignments/homework-two folder
