### ISSUE TITLE
Lab homework question

### ISSUE THREAD

**Issue by motazb** [ShawnTylerSchwartz/eeb-c177-w20#14]
For the first question on the Darwin’s Theory text, I was able to highlight all the words starting with an s, but my command line is also highlighting the s after the apostrophe in the word “man’s” and I can’t understand why at all.
Here is my command line:
\bs\w*\b

**Comment by Deap-Bhandal** [comment]
Since there are no words that only have s in them, I think you should consider replacing the * to something that does at least 1 instance.

**Comment by shawntz** [comment]
Nice suggestion @Deap-Bhandal !
