### ISSUE TITLE
Lecture HW Part 3

### ISSUE THREAD

**Issue by Deap-Bhandal** [ShawnTylerSchwartz/eeb-c177-w20#16]
For the 10 records we extract to Pacifici-ten.txt, are they just the family column or all the columns?

**Comment by shawntz** [comment]
@Deap-Bhandal for the `Pacifici-ten.txt` file, you will grab all columns, but just the first 10 records (rows). Part 5 of this assignment is where you will select certain columns (which are outlined for you in that problem description in the homework specifications).

**Comment by Deap-Bhandal** [comment]
Got it. Thank you!
