### ISSUE TITLE
Regex Lab Part 2 General Questions

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#17]
Hello all,

Firstly, I seem to be having an issue with finding things that are associated with something else while excluding that something else. For example, for the first question for part 2, I wrote \ss\w+ to look for collections of characters that start with a space and end with at least one alphanumeric character. This gives me the words that start with s as well as the spaces before them. According to the tutorial, putting parentheses around (s\w+) should exclude the space before the word, but that didn't seem to work in Sublimetext.

Secondly, are regex searches supposed to be case-sensitive? In class and in the Regexone activities that appeared to be the case, but I'm using Sublimetext and it seems to interpret A and a equivalently.

Thank you so much!

**Comment by shawntz** [comment]
@omerlavian20 sorry for the late reply on this. Is this still something that you would like me to go over, or can we close this issue? Let me know, thanks!

**Comment by omerlavian20** [comment]
You can close it. Thank you!
