### ISSUE TITLE
HW2 PT. 2 Q1(2)

### ISSUE THREAD

**Issue by LinhN16** [ShawnTylerSchwartz/eeb-c177-w20#18]
I am trying to use the pipe command, but I keep getting an error saying that Permission is denied.
I have tried:
1. ~/developer/repos/eeb-c177-homework/class-assignments/homework-two$ Pacifici-25lines.txt | wc -w
- the issue I run into when I'm here is command is not found so I went back to class assignments
2. ~/developer/repos/eeb-c177-homework/class-assignments$ ./homework-two/Pacifici-25lines.txt | wc -w
- the issue I run into here is that Permission is denied

This is for Q1 at the end of Part 2 of Homework 2. Thank you in advance!

**Comment by omerlavian20** [comment]
Do the head command to peak at the first 25 lines then use the | with that.

**Comment by LinhN16** [comment]
Gotcha, thank you! I was able to use the pipe command going back into the data folder where the Pacifici2013_data.csv file is held, then used the command:

head -n 25 Pacifici2013_data.csv | wc
