### ISSUE TITLE
Git Push Origin Master Issue?

### ISSUE THREAD

**Issue by soniavsd** [ShawnTylerSchwartz/eeb-c177-w20#19]
I keep trying to push my commits to github, but when I type in my user and password after "git push origin master" it says:
 remote: Permission to StefanoAllesina/CSB.git denied to soniavsd (my user). fatal: unable to access 'https://github.com/StefanoAllesina/CSB.git/'
 How to fix this?

**Comment by shawntz** [comment]
@soniavsd Please see my response to issue #11  where I explained what is going wrong here (https://github.com/ShawnTylerSchwartz/eeb-c177-w20/issues/11)
