### ISSUE TITLE
Help with entering into my week one folder in terminal

### ISSUE THREAD

**Issue by soniavsd** [ShawnTylerSchwartz/eeb-c177-w20#2]
Hi everyone! 
I'm sure I am missing a step but I can't quite remember what to do. I opened the terminal after shutting it down and tried to enter a directory by entering cd Developer (the one we created in class). However, it keeps saying that No such file or directory exists. What step did I miss??

**Comment by shawntz** [comment]
Hi @soniavsd, in your Terminal, what happens when you type `pwd` and `ls`? Attach the output here so I can see where you are at.

**Comment by soniavsd** [comment]
It says: /home/eebc177student

**Comment by shawntz** [comment]
@soniavsd okay great, and what happens when you type `ls`?

**Comment by soniavsd** [comment]
I GOT IT TO WORK! Apparently I accidentally created another virtual machines so nothing was configured yet!! Thank you for your help!!

**Comment by shawntz** [comment]
Okay great @soniavsd!
