### ISSUE TITLE
Homework 3 Part 1

### ISSUE THREAD

**Issue by goharmihranian** [ShawnTylerSchwartz/eeb-c177-w20#20]
Hi!

I'm having trouble understanding what we're supposed to do for number 4...
I really don't understand how we'll find the most occurrences of each category after 1901
Can someone please guide me?

**Comment by goharmihranian** [comment]
Also having trouble with number 3 for part 2
Ive tried using cut and grep twice, separated by pipes but specifying the columns but I can't seem to get it organized the way the question is asking

**Comment by shawntz** [comment]
@goharmihranian this problem is a good example of one that would best be solved by thinking about how you can break this big problem into smaller subproblems. Logically trace out the steps that you need to accomplish along the way (each substep: i.e., what you'd be piping from each step-to-step). Also consider what your **input** and anticipated **outputs** are. In the end, you want to find which category of Nobel prize (`chemistry`, `economics`, `literature`, `medicine`, `peace`, `physics`) occurs the most, and which occurs the least. Think through this type of thought process and see if you can piece it apart.

**Comment by shawntz** [comment]
@goharmihranian you don't have to use `cut` twice to solve that problem. Put the script that you're working on up here so we can work through where things might be going wrong

**Comment by goharmihranian** [comment]
@ShawnTylerSchwartz 
cut -d "," -f 4-10 European_Red_List.csv | grep -w AVES | grep -w -E 'PASSERIFORMES|ACCIPITRIFORMES|ANSERIFORMES|BUCEROTIFORMES|CAPRIMULGIFORMES|CHARADRIIFORMES' | grep -E 'EX|RE|CR' | grep -v -E 'EN|VU|NT|LC|DD|NA' | sort | uniq -c

this is what I have so far and its working but I'm wondering if there's any easier way to do this without typing out each order possible?

**Comment by goharmihranian** [comment]
would sort -k 5 work? I'm just not sure how that would do it though

**Comment by shawntz** [comment]
@goharmihranian Sorry for the delay in reply as promised earlier, I had some unexpected meetings that came up.

Your desired output should look something like this:
```
   1 ACCIPITRIFORMES,CR
   3 CHARADRIIFORMES,CR
   2 CHARADRIIFORMES,EX
   1 CHARADRIIFORMES,RE
   1 OTIDIFORMES,CR
   3 PASSERIFORMES,CR
   1 PASSERIFORMES,RE
   1 PELECANIFORMES,RE
   1 PROCELLARIIFORMES,CR
   1 STRIGIFORMES,CR
   1 SULIFORMES,RE
```
Consider first using `grep` to first grab all of **AVES**  from the `European_Red_List.csv`. Then look into the `grep -w` function, which can help you search for _full words_. These are some **hints** that can help everyone with solving this problem. Then using the rest of the commands you have learned to make the output look like what I have attached above.

**Comment by omerlavian20** [comment]
I can see how to do this by going family by family and category by category. Is it possible to, in one or several commands, get the exact output you put up?

**Comment by goharmihranian** [comment]
I figured it out. You need to use grep AVES | grep -E 'EX|RE|CE' and then do the same with the negating command -v Dr. Alfaro used in class today to exclude the others

@omerlavian20

**Comment by omerlavian20** [comment]
How is the negating command useful? @goharmihranian

**Comment by omerlavian20** [comment]
I did grep -w -E "EX|RE|CR" and got all the extinct/near extinct birds. Now I just don't know how to get rid of all the stuff between the order and the category to get the above output. @goharmihranian @ShawnTylerSchwartz

**Comment by goharmihranian** [comment]
Sorry, I'm just seeing this. I guess it works without it too but I didn't know that until after I turned it in. grep -v just says don't include this in my output from what I understood
