### ISSUE TITLE
Homework #3 Part 2

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#21]
So I am most of the way through this assignment, but I am stuck on the last problem. I am able to find the number of entries for each order or birds, and I could finish the assignment by using head and tail to extract the data from each order and find the number in each category that way, but I feel like there should be a more efficient way to do this. Can anyone offer some insight that might be helpful?

**Comment by shawntz** [comment]
@omerlavian20 check out my comment here (https://github.com/ShawnTylerSchwartz/eeb-c177-w20/issues/20#issuecomment-577943359)
