### ISSUE TITLE
Lecture Homework 3: Part 1

### ISSUE THREAD

**Issue by dylanreadel** [ShawnTylerSchwartz/eeb-c177-w20#22]
I'm having trouble finding a difference in the code I would be using for questions 1 and 4, and I assume two questions wouldn't require the same input. In question 1, the question asks to find the number of winners for each Nobel prize category which I think I completed successfully. Questions 4 asks to find the Nobel prizes that were awarded the most and least, but wouldn't that be the same code as question 1 (finding the number of each prize would tell me which one was awarded the most and least)? Or am I misunderstanding one of these questions?

**Comment by shawntz** [comment]
@dylanreadel Good question, let me clarify what the questions are asking and provide some hints. For the first question, you only need to filter through by _Nobel prize category_ and get the counts. For the fourth question, think about the steps that you did to solve the first problem, but now filter by _date (i.e., year)_ along with _Nobel prize category_. 

Essentially, the first problem you are getting counts of each _Nobel prize category_ **without including the year column**, and the fourth problem you are getting counts of each _Nobel prize category_ **with the year column**.

Let me know if this clarifies things.

**Comment by dylanreadel** [comment]
Yes, this makes sense, thank you!
