### ISSUE TITLE
#Lab 4 Part 2

### ISSUE THREAD

**Issue by jpocon** [ShawnTylerSchwartz/eeb-c177-w20#25]
Hi all, I'm questioning my interpretation of the last question in our lab homework:

> 3. How would you find the largest change in inflammation for each patient? 

Is this asking for the largest difference between max and min across each row (i.e. largest overall change in inflammation per patient)? 

Or is it looking for the largest sequential difference between adjacent values in each row (largest change in inflammation from one day to the next per patient)?

**Comment by shawntz** [comment]
Hi @jpocon, thinking about this question as you posed it here: 

> Is this asking for the largest difference between max and min across each row (i.e. largest overall change in inflammation per patient)?

is a fine way to think about it. If you need to solve these problems (now or in the future), always consider that you may (or may not) need to get the absolute magnitude for these data if the value differences are negative (and negative outputs are not what you were expecting).
