### ISSUE TITLE
Week 4 HW part 1 error loading file on python

### ISSUE THREAD

**Issue by motazb** [ShawnTylerSchwartz/eeb-c177-w20#26]
![Screenshot (4)](https://user-images.githubusercontent.com/59575908/73322834-498f9f00-41fa-11ea-9c65-2eab63aca8d0.png)

I get this error when I try to upload my data set on Python

**Comment by shawntz** [comment]
@motazb the error is due to some (or all) numerical floating point values in your data set are possibly encoded as strings within the .csv file. Could you please email me a copy of your data file so I can take a look at it and see what the problem is? Then I can give you a solution to fix it.

**Comment by shawntz** [comment]
@motazb I was looking through your file and I think it is having trouble parsing the field with the dates (it is treating them as a string). As such, one work around is to use a module called `pandas`, and then convert it to a `numpy` ndarray. I have provided the code that would accomplish this for you below. You would then select the relevant columns to do your analyses on.

```Ipython
import pandas as pd
tmp_data = pd.read_csv('nss15.csv')
data = tmp_data.to_numpy()
```

The new `data` file will house the numpy ndarray of the data. You could also look into manipulating the `pandas` data frame if you would like to read up on documentation and what you could do with it.

**Comment by motazb** [comment]
Got it! Thank you!
