### ISSUE TITLE
Week 4 HW part 2 Stacking Arrays

### ISSUE THREAD

**Issue by motazb** [ShawnTylerSchwartz/eeb-c177-w20#27]
![Screenshot (5)](https://user-images.githubusercontent.com/59575908/73420272-d445cc00-42d6-11ea-8c1c-644950aefbe8.png)
is my answer supposed to look like this? Or does it need to not repeat?

**Comment by shawntz** [comment]
@motazb the question asks for a 3x2 arrays as the output (which is expected to be a 3-row by 2-column array). Your current output is a 4x3 array, which is not correct.
