### ISSUE TITLE
Lab 4 Hw part 2

### ISSUE THREAD

**Issue by soniavsd** [ShawnTylerSchwartz/eeb-c177-w20#29]
Hello! I've been working on the stacking arrays portion of the homework, but I cannot get the correct answer. I  have the line:
print("first and last column of A=", (A[1:-1]))
but it gives me the middle row (4,5,6)
what am I doing wrong?

**Comment by Deap-Bhandal** [comment]
I would find the first column of A, find the last column of A and then stack them.
