### ISSUE TITLE
when I do git commit -m "xxxx" I get an error

### ISSUE THREAD

**Issue by motazb** [ShawnTylerSchwartz/eeb-c177-w20#3]
The error says "On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean"

If I try git push origin master I get an error:
"error: failed to push some refs to 'https://github.com/motazb/eeb-c177-homework.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."

**Comment by shawntz** [comment]
@motazb This type of issue occurs when the remote version of the repository (i.e, GitHub) has changes that were made that are out of sync with the one locally stored on your computer.

Can you try the following to see if this solves your problem? If not, let me know and we can try something else.

First do:
`git pull`

Then do:
`git push origin master`

**Comment by motazb** [comment]
that fixed it! Thank you!
