### ISSUE TITLE
Downloading Python Book From VPN

### ISSUE THREAD

**Issue by goharmihranian** [ShawnTylerSchwartz/eeb-c177-w20#30]
I'm having trouble downloading the book from the VPN. Can anyone help?

**Comment by shawntz** [comment]
@goharmihranian sure thing, where is the problem arising? Can you provide some more details about the issues you're experiencing?

**Comment by goharmihranian** [comment]
It worked and let me access it but is there anyway to download it so I have it on my desktop or do I have to go to the website every time?

@ShawnTylerSchwartz

**Comment by shawntz** [comment]
@goharmihranian from what I understand, you can only view the book online, not download it as a PDF.
