### ISSUE TITLE
Making the delimiter dynamic

### ISSUE THREAD

**Issue by motazb** [ShawnTylerSchwartz/eeb-c177-w20#32]
If I try to use $3 to make the delimiter dynamic, I get an error saying "cut: the delimiter must be a single character."
Is there a different way to set the delimiter to be dynamic?

**Comment by shawntz** [comment]
@motazb when you call the script and parameters inside of the terminal, what are you passing as an argument? Copy and paste your call to run the script that is producing this error here so I can try and see what the problem is.

**Comment by motazb** [comment]
ExtractBodyM.sh ~/Developer/repos/CSB/unix/data/Pacifici2013_data.csv BodyM.csv ;
This is the line I type to try to run it while defining the delimiter to be a semicolon

**Comment by shawntz** [comment]
@motazb try this: `ExtractBodyM.sh ~/Developer/repos/CSB/unix/data/Pacifici2013_data.csv BodyM.csv ';'`

What happens when you run this instead?

**Comment by motazb** [comment]
it gives me the same error "cut: the delimiter must be a single character"

**Comment by shawntz** [comment]
@motazb what does your actually implementation of the code in your script look like?

**Comment by motazb** [comment]
tail -n +2 $1 | cut -d '$3' -f 2-6 | tr -s '$3' ' ' | sort -r -n -k 6 > $2

**Comment by shawntz** [comment]
@motazb the problem is that you `$3` are in single quotes. Just put `$3` by itself and see what happens.

**Comment by motazb** [comment]
Yes.. That worked. I had tried "$3" and every other way to do it except that.
Thank you!
