### ISSUE TITLE
Week 5 plotting HW Part 1

### ISSUE THREAD

**Issue by motazb** [ShawnTylerSchwartz/eeb-c177-w20#34]
Part 1 #2 asks to display "the three plots on top of one another instead of side by side." Does this have anything to do with #1 asking to plot the standard deviation? Or by three plots do you mean the minimum/maximum/average which we did in lab?

**Comment by shawntz** [comment]
@motazb By three plots I mean the minimum/maximum/average plots that we had originally done in lab
