### ISSUE TITLE
Chapter 8 dict() vs defaultdict()

### ISSUE THREAD

**Issue by Deap-Bhandal** [ShawnTylerSchwartz/eeb-c177-w20#36]
For chapter 8, they mention creating a dictionary using `dict()`. They said it has some limitations such as the key cannot be name used for something else. Do the same limitations apply to `defaultdict()`? Since `defaultdict()` is less error prone for a key not having a value, is it better to have `defaultdict()` in all cases?

**Comment by shawntz** [comment]
@Deap-Bhandal 
> "The defaultdict tool is a container in the collections class of Python. It's similar to the usual dictionary (dict) container, but the only difference is that a defaultdict will have a default value if that key has not been set yet. If you didn't use a defaultdict you'd have to check to see if that key exists, and if it doesn't, set it to what you want." --https://www.hackerrank.com/challenges/defaultdict-tutorial/problem

Thus, if you have a scenario where it would be beneficial to check and see if a key exists, you should go with `dict()`, however, if you are writing a problem where it doesn't matter if that value already exists or not, then `defaultdict()` is probably a safer way to go to avoid accidentally throwing an error. If you had a key that was the same name as something else, it would just be another occurrence of that key within the dictionary, regardless of whether it was a `dict()` or a `defaultdict()`.

**Comment by Deap-Bhandal** [comment]
I see, thank you!
