### ISSUE TITLE
General Question related to 8.6 in the Hw

### ISSUE THREAD

**Issue by KaranSingh-14** [ShawnTylerSchwartz/eeb-c177-w20#38]
If we create a multilevel dictionary and want to want to add another key with its own distinct values, do we just use the append function with the name of the multilevel dictionary to add it to the list? Or is it that we just use the multi dictionary name then put ['Insert Key here']= 'value'? Thank you

**Comment by chausteven** [comment]
From what I have read from the book and tried on python, I think the append() function only works with lists and cannot be used as a function for dictionaries. I would just use the ['Key']='value' syntax to add another key and value into the dictionary.
