### ISSUE TITLE
Posting the markdown file on forum 

### ISSUE THREAD

**Issue by shreyatrivedi26** [ShawnTylerSchwartz/eeb-c177-w20#40]
Is there any way in which I can post a markdown file for the homework on chapters 6-8? 
I tried to copy the markdown text to the comment but it is very difficult to read the codes and solutions like that. 
I could only push it but couldn't upload it here.

**Comment by shawntz** [comment]
@shreyatrivedi26 these comment boxes on the GitHub issues render markdown, so it shouldn’t be a problem if you copy and paste markdown into here

**Comment by shreyatrivedi26** [comment]
[HW-Introduction to Python (Ch-6-8).pdf](https://github.com/ShawnTylerSchwartz/eeb-c177-w20/files/4179410/HW-Introduction.to.Python.Ch-6-8.pdf)

Thank you Shawn! 
I tried to copy and paste the .md files here. It did not work out well. 
So I have converted the markdown into a pdf and attached the same. 

I hope it helps :)
