### ISSUE TITLE
HW 6 ch 8.12 exercise

### ISSUE THREAD

**Issue by motazb** [ShawnTylerSchwartz/eeb-c177-w20#41]
When trying to solve this I get an error saying "can only concatenate str ( not "int") to str.
This is what I tried:
numbers = range(10)
for numbers in range(10):
    print('Got ' + numbers)

**Comment by soniavsd** [comment]
i think you're missing a str, try this: 
for numbers in range(10):
    print('Got ' + str(numbers))

**Comment by motazb** [comment]
yes! that fixed it. Thank you.
