### ISSUE TITLE
Lab Week 6 Jupyter Notebook

### ISSUE THREAD

**Issue by chausteven** [ShawnTylerSchwartz/eeb-c177-w20#43]
I was wondering if you could possibly post the Jupyter Notebook for today's lab (2/10) as my computer ran out of battery during lab and I could not practice the code myself. 

Thanks,
Steven

**Comment by shawntz** [comment]
@chausteven up to which point did you get to before your computer died?

**Comment by chausteven** [comment]
Up to the point where we created a visualize function.

**Comment by shawntz** [comment]
@chausteven I posted the code on CCLE under a new "Lab Code" section
