### ISSUE TITLE
Help with pushing to the new repository

### ISSUE THREAD

**Issue by soniavsd** [ShawnTylerSchwartz/eeb-c177-w20#44]
I did all the steps to push the eeb-c177-project new repository, but it says: remote: Not Found
fatal: repository 'https://github.com/soniavsd/' not found
whenever I git push -u origin master. 
Ive already committed it for a timestamp, but I dont know how to fix this.

**Comment by omerlavian20** [comment]
I just followed this tutorial and it seems to have worked.
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository

**Comment by shawntz** [comment]
@soniavsd were you able to resolve this issue? Let me know so that I can provide assistance (if still needed).

**Comment by soniavsd** [comment]
@ShawnTylerSchwartz Yes I got it, just forgot to close the issue, sorry!
