### ISSUE TITLE
Lecture Homework #8: Question 2

### ISSUE THREAD

**Issue by dylanreadel** [ShawnTylerSchwartz/eeb-c177-w20#47]
I'm working through question 2a right now in lecture homework #8, but I can't think of any solutions to solve it. I assume I have to use a function to search each line of the Dalziel2016_data.csv file to find lines that match the year 1920, but I don't recall learning any. I have read about using regular expressions within Python in the textbook and online, but I can't find any help that I can understand and apply to this specific problem. Has anyone had any success with this problem? I can't move on to the rest of the homework because the problems are very similar to 2a (searching the file for key words).

**Comment by shawntz** [comment]
@dylanreadel were the contents of this question resolved after going through the code exercises in lecture last week? Let me know so that I can provide assistance (if still needed).
