### ISSUE TITLE
Outfiles not appearing in Github

### ISSUE THREAD

**Issue by alexphu1230** [ShawnTylerSchwartz/eeb-c177-w20#49]
I am working on 2a and 2b and think that I wrote the code correctly to create an outfile. I used the following code and when I run the code, there are no errors but when I push to github, there are no new outfiles. Is anyone else having trouble with this?

for column in csv_file:
    if word == column[2]:
        print (column)
        data2= column
        for col in range (4):
            output_file.write(data2[col] + ",")
        output_file.write(data2[4] + "\n")
        
output_file.close()

**Comment by shawntz** [comment]
@alexphu1230 sorry for the delay in response to this. Were you able to get this resolved or do you still have a question about this? Let me know so I can provide assistance (if needed).
