### ISSUE TITLE
Lecture Homework 9: Running Python Script from Command Line

### ISSUE THREAD

**Issue by dylanreadel** [ShawnTylerSchwartz/eeb-c177-w20#50]
I am having trouble running my python script from the command line. I have taken a function directly from my previous final project assignment and copied it into a text file in Atom, saving it as a .py file called project-analysis-script.py. I included all the required library imports (e.g. import pandas as pd) in the text file, and at the end of the script I have a line that runs the function with the desired input csv file I want to analyze.

>>> `visualize_occurrences_by_season('iNaturalist-birds-LARW.csv')`

 However, when I run `$ python project-analysis-script.py` in the command line, I get an error that says my csv file could not be found. I tried two solutions: using the full file path in the .py file and copying the csv to the same directory as the python script. Neither have worked and return the same error. Any help would be appreciated, thanks!

**Comment by LinhN16** [comment]
Alex and I are having the same issues as Dylan.

The error message I get particularly is that there is an invalid syntax in the title:
def dynamic_plot('pima-indians-diabetes.csv'):

and the syntax error shows an arrow hovering below the second end quote for the title of my csv file.

**Comment by omerlavian20** [comment]
This may not work but this helped me once. When you write the path try to the file try making sure that you represent the home directory as "home" and not "~". Alternatively, go to the location of the file you want to use, type "pwd", and copy the result into your code.

**Comment by shawntz** [comment]
@omerlavian20 that's a great suggestion (using "home", not "~"; along with pwd to get the exact location to copy-and-paste). If you all still aren't able to get it working, upload your script assuming the file path "works" and then we can try to debug them in lab tomorrow or office hours this week. I would definitely recommend trying what Omer suggested though, as that is what my first thought would be. 

Another question I would ask is: where is your `.py` file located on the computer relative to the data file that you're trying to use? If you move them to the same directory, do you still get an error? Think about whether there may or may not be read-write privilege issues (thought I wouldn't think this would be the case, it may be worth investigating just to make sure).
