### ISSUE TITLE
Swirl Download

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#57]
So I tried downloading swirl multiple times and I got a message that looked like the download was successful, but then when I would do library("swirl") it would tell me that it wasn't installed. I included a screenshot to show what I was looking at. 
![swirl issue](https://user-images.githubusercontent.com/59575888/75845965-96353f80-5d8f-11ea-8441-1d954f84042f.JPG)

**Comment by shawntz** [comment]
@omerlavian20 what happens if you do `library(swirl)` instead `library(“swirl”)`?

**Comment by omerlavian20** [comment]
> library(swirl)
Error in library(swirl) : there is no package called ‘swirl’

**Comment by shawntz** [comment]
@omerlavian20 try restarting RStudio or even your virtual machine all together

**Comment by dylanreadel** [comment]
I received the same error, restarted RStudio and the virtual machine, but I am still getting the error that the installation of the swirl package had non-zero exit status.

**Comment by Deap-Bhandal** [comment]
I too have the same error.

**Comment by KaranSingh-14** [comment]
I am also getting the same error and tried to restart the whole thing but no luck

**Comment by jpocon** [comment]
Also getting the same error... restarted (both R and VM), and reinstalled "swirl" ... will keep troubleshooting

**Comment by jpocon** [comment]
https://github.com/swirldev/swirl/wiki/Common-Errors-and-Fixes

could the VM be the issue? looks like we need a comp with full permissions granted - on my phone now, but will try swirl in R outside the VM

**Comment by omerlavian20** [comment]
If one of you goes to the hacking sesh today and figures out the issue can you post here about what you did?

**Comment by jpocon** [comment]
update: swirl works on my personal os, the vm might be the issue

**Comment by shawntz** [comment]
Hi everyone,

I just tried installing this on a fresh install of R just to look into it and it works fine for me. I think it might be a VM issue. If you are able to get this installed on your personal machine, it would be an invaluable tool for you to use to learn the essentials of R.

**Comment by shawntz** [comment]
Okay, please go into your Terminal on your VM and run the following command:

`$ sudo apt-get install libcurl4-openssl-dev`

This is an essential library that is needed (which in @omerlavian20's output says there is an error with this missing). As such, if you install this, then retry installing `rswirl` with `install.packages("swirl")`, see if you are then able to use it with `library(swirl)`. 

This should (hopefully) solve the issue.

**Comment by alexphu1230** [comment]
Hi Shawn, 

I ran the command you posted in terminal and after trying to reinstall swirl I still get that "'swirl' had non-zero exit status"

**Comment by omerlavian20** [comment]
@alexphu1230 or anyone else still struggling with this for that matter I got R and R studio on my actual computer and it's all working fine. Also it took a few seconds to download each one so I would just do that.
