### ISSUE TITLE
How to differentiate colors on a k-means cluster plot

### ISSUE THREAD

**Issue by soniavsd** [ShawnTylerSchwartz/eeb-c177-w20#58]
How could I tell which categories each color stood for on this graph?
![Screen Shot 2020-03-07 at 5 01 37 PM](https://user-images.githubusercontent.com/59575895/76154722-144a5c80-6096-11ea-8e4d-0dea107bd233.png)

**Comment by shawntz** [comment]
@soniavsd the way that you can differentiate the colors is by printing out the `y_pred` labels variable side-by-side with the list of countries that match those points. If you separate all of the names of the country by their corresponding `y_pred` cluster number, you can get an idea as to which points are clustered together (and then infer reasons/possible explanations as to why those points may be clustered together).
