### ISSUE TITLE
Object Not Found Error in ggplot2

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#59]
I'm trying to make a boxplot with data that I've loaded in, and even though I specified the column in the dataframe I want to analyze I get an error that I cannot seem to fix. Anyone have [suggestions?]
![urbannative](https://user-images.githubusercontent.com/59575888/76159554-b8ec8e80-60d6-11ea-90a7-bca7fee796ce.JPG)

**Comment by shawntz** [comment]
@omerlavian20 remove the `-` between your variable names. Either use `_` or nothing. That seems to be the reason why you are facing this error (the interpreter is breaking off the string "Urban" because there is a `-` directly following that and it therefore doesn't recognize it as a variable name.
