### ISSUE TITLE
Linking Python notebook properly for presentations

### ISSUE THREAD

**Issue by robertreny** [ShawnTylerSchwartz/eeb-c177-w20#60]
Hi @ShawnTylerSchwartz ,

Does linking the github link to our jupyter notebook work for the presentation? So mine would look like: https://github.com/robertreny/eeb-c177-project/blob/master/analyses/Data%20for%20mapping.ipynb

Thanks,

Robert

**Comment by shawntz** [comment]
@robertreny That sounds good to me! The link works fine and can be a fast and easy way to show your Python code during your lightning talk.
