### ISSUE TITLE
Markdown/LaTeX/Notebook for Presentations

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#63]
So I understand that we need to make our presentations nice, but according to the guidelines (if I understand correctly) we are supposed to use Markdown and LaTeX in our presentations. Is there a way to type Markdown or LaTeX directly into Powerpoint or should we type such formatted text and paste screenshots of it into the slideshow?
Thanks in advance!
![markdown](https://user-images.githubusercontent.com/59575888/76395668-17af4380-6335-11ea-86e8-4aca49a4e827.JPG)

**Comment by shawntz** [comment]
@omerlavian20 you can generate the markdown/LaTeX code and then screen shot it and place it into your slides if you'd like. Just make sure that the code is readable. You can also use the listings package with LaTeX and then screen shot that output and place it into your slides.
