### ISSUE TITLE
Jon - Lightning Talk

### ISSUE THREAD

**Issue by jpocon** [ShawnTylerSchwartz/eeb-c177-w20#64]
[Access my EEB-C234 Lightning Talk here](https://youtu.be/2-DO_I6c6qA). 

Topic: Mapping Global Tropical Dry Forest Extent
Code Demo in R using the Tidyverse and Ggplot2.

**Comment by omerlavian20** [comment]
Great talk! I watched Shreya's talk before this, and I noticed that she used both Python and R to place data on maps. You mention mapping with R here, but did you use Python for this purpose as well? If so, did you find one more helpful to you than the other for mapping definitions? Did you find that, like with standard graphs (line graphs, boxplots, etc.), it is easier to get more detailed data visualizations in R?

**Comment by jpocon** [comment]
Thanks Omer! I did use Python as well, but not for mapping. I haven't watched Shreya's talk yet, but I believe Python is much easier when working with her data type (netCDF). I used it mainly for data manipulation (GeoTiffs), then R for all my visualizations because (in my opinion) they are prettier and easier to create in R over Python.

**Comment by LinhN16** [comment]
Remote sensing is such a revolutionary means of data gathering and your explanation of how it works was concise, yet informative. It was cool seeing the maps you created using the data in your dataset and seeing how you overlayed the definitions because it helped understand how mapping works in figures that we often see in scientific articles.

**Comment by jpocon** [comment]
@LinhN16 Thanks for the comment! I agree with you, when I first learned to map through code (instead of GUI software like ArcGIS or QGIS), I began noticing the similarities with figures in scientific articles. It also became evident how much faster it is to map in R and/or Python vs. GUI software. Very useful for big data sets like mine, and much easier to edit just a few lines of code.

**Comment by goharmihranian** [comment]
I thought it was really cool how you showed us step by step how the data is acquired. I actually had no idea about your research or methods of obtaining the data and you did a really great job of explaining it in enough detail to give me the full picture! You mentioned doing some statistical testing; what types of statistical tests do you run for the parameters mentioned and how do you interpret those results?

**Comment by shreyatrivedi26** [comment]
Really liked your presentation! (Especially the part at 0:40 where you talk about temperatures as a climatic parameter affecting the tropical dry forests :D).
What I can see in your codes is that you are trying to study the distribution of dry forests in various climatic types. Additionally, I see boxplots used as one of your visualizations.  Did your study also try to map the variability in any particular variable? If yes, what all statistical measure of variability did you use  or plan to use for the same?

**Comment by altaing** [comment]
Hi Jon, really great and informative presentation! The flow of the slides/diagrams made it very easy to follow and much easier to understand. You mentioned you used R and ggplot2 for your functions and plots. I am curious to how much of this you were able to achieve just using Python. Were you able to get any statistical data to tell whether or not your findings were significant?

**Comment by jpocon** [comment]
@goharmihranian @shreyatrivedi26  Hi, thanks for the feedback! It is all super helpful. That said, a common question among y'all has to do with which stats we used. It depends on the regions we choose to compare against -- countries, biodiversity hotspots, ecoregions, subcontinents, etc. -- some of these have high sample sizes (i.e. countries) so we can run normality tests and paired t-tests as we would on most other data sets, but when we want to compare small smaple sizes like subcontinents, we used a Shapiro-Wilk normality test and Mann-Whitney-Wilcox nonparametric test.

@altaing Hi, thanks for your comment! As for stats, please see above in my response to Gohar and Shreya. As for R vs. Python, about 95% of my analysis is done in Python. Everything from data ingestion, manipulation, band math, etc. that is all Python code. The remaining 5% is reserved for mapping, plotting in R - because it's prettier.

**Comment by WhitneyTsaiNakashima** [comment]
Great work! I like that you are using remote sensing to define TDF because it is such cool habitat, but definitely pretty variable depending on where you are. Did you find certain definitions to be better (covering more actual TDF) than others and do you think there is a way to define all TDF or would it be better to make multiple habitat categories?

**Comment by estmendoza** [comment]
Hi Jon! I really liked how you walked us through the concept of TDF and the way data is collected for mapping purposes. I was wondering what kind of plot you think works best for the comparison of these datasets?

**Comment by jpocon** [comment]
@WhitneyTsaiNakashima Thanks! We did find that certain definitions were better for different regions (i.e. Dryflor TDF definition captured a lot of TDF extent in Latin America), but our hope is to find the best global definition. Our impetus for this project was that we were going to use the WWF TDF Ecoregions, but these hardly captured any verified TDF plots. We are close to a finding, so will keep you in the loop!

@estmendoza Glad I was able to do so in the time alotted! I personally like the stacked density, but faceted may be best since it disaggregates the deifnitions and allows for a cleaner comparison. The box plots are nice, but one of the deifnitions we tested had some huge outliers (overestimates the presence of TDF) and I think the density plots captured this in a cleaner visual.

**Comment by dylanreadel** [comment]
Great analysis, dry forests are incredibly impacted especially on islands like Hawaii, so I appreciate that you care so deeply about them. Certain species of plants are only found in dry forests, so I was thinking that they might be a great indicator of the true extent of the forests. Have you considered using species locations as an alternative to understanding the dry forest regions in different parts of the world?

**Comment by jpocon** [comment]
@dylanreadel Thanks for the feedback! There are a number of TDF analyses that have and are doing just this. Many of our 500+ verified locations of global TDF come from these studies, and a future project of ours will be focused in Hawaii! Super exciting work. This paper is rather looking to establish consensus on the _climatic_ definition of TDF on a global scale, then compare it protected areas, ecoregions, and these more species-specific plots.
