### ISSUE TITLE
Karan Singh Lightning Presentation

### ISSUE THREAD

**Issue by KaranSingh-14** [ShawnTylerSchwartz/eeb-c177-w20#67]
Species Coexistence
Youtube Link: 
https://youtu.be/DTgMnRZRtEU

**Comment by omerlavian20** [comment]
Awesome job! Your visualizations very clearly showed the trend you were describing. Have you tried testing if the differences in coexistence values across dry versus arid sites were statistically significant? If so, what tool(s) did you use? For my data, I ran a one-way ANOVA with several variables using scipy.stats, which would be applicable here.

**Comment by LinhN16** [comment]
Interesting find that there is higher biodiversity found in areas of low aridity. Future studies could perhaps uncover potential factors that play a role in why biodiversity changes with different conditions; this could then be useful in future conservation projects, especially when determining what species would fare best in diff temperatures (since climate change is a very pressing issue currently).

**Comment by jessicadeanda** [comment]
Great presentation! The plot you generated is clear and easy to interpret. I also think it would be beneficial to assess the statistical significance of your data and possibly use geom_errorbar() to add error bars to your plot. If you decide to add error bars, you may want to select a different color for your bars.

**Comment by shreyatrivedi26** [comment]
Great talk! 
I was just wondering how your datatset looked like? Was the sites pre-defined or were they based on some threshold rainfall values (i.e. a minimum rainfall which categorizes a particular site as arid or semi-arid)? 
Besides, the plots could have been more intuitive if you would have tried to make one single plot incorporating both the variables which would have further made your comparisons visually appealing and easier to follow. 
Another easy way to study relations between the sites and  transect codes is to look for some correlation coefficients or linear models (geom_smooth) and plotting them to show any kind of inter-dependence between the two.

**Comment by haonguyen318** [comment]
Hi Karan! I like the format of your presentation and how it looks visually. It is very organize and easy to follow through your explanation and data analysis. I also like how you highlighted the challenges that you faced throughout this project and how you overcame those challenges. I also noticed that you used Latex to write out your code which makes it look much neater and easier to follow through. Your plots gave a great visualization of the data at hand and you gave a very thorough explanation of what the graphs mean. Overall great job on your presentation!

**Comment by robertreny** [comment]
Hi @KaranSingh-14 your presentation looks really great and I thought you walked through your thought process and coding really well. I liked that you explicitly stated the coding challenge both verbally and over text. I especially liked the use of "checks" in your code to make sure steps were done correctly.

**Comment by KaranSingh-14** [comment]
> Hi @KaranSingh-14 your presentation looks really great and I thought you walked through your thought process and coding really well. I liked that you explicitly stated the coding challenge both verbally and over text. I especially liked the use of "checks" in your code to make sure steps were done correctly.

Thank You Robert! I tried to make the presentation as easy to follow as I possibly could and decided to add some background information to cover the necessary information needed in order to adequately provide you guys with the data.

**Comment by KaranSingh-14** [comment]
> Hi Karan! I like the format of your presentation and how it looks visually. It is very organize and easy to follow through your explanation and data analysis. I also like how you highlighted the challenges that you faced throughout this project and how you overcame those challenges. I also noticed that you used Latex to write out your code which makes it look much neater and easier to follow through. Your plots gave a great visualization of the data at hand and you gave a very thorough explanation of what the graphs mean. Overall great job on your presentation!

Thank you for the kind words. Like I have replied back to Robert, my goal was to make the presentation as coherent as possible without making it a drag to get through the material!

**Comment by KaranSingh-14** [comment]
> Great talk!
> I was just wondering how your datatset looked like? Was the sites pre-defined or were they based on some threshold rainfall values (i.e. a minimum rainfall which categorizes a particular site as arid or semi-arid)?
> Besides, the plots could have been more intuitive if you would have tried to make one single plot incorporating both the variables which would have further made your comparisons visually appealing and easier to follow.
> Another easy way to study relations between the sites and transect codes is to look for some correlation coefficients or linear models (geom_smooth) and plotting them to show any kind of inter-dependence between the two.


Thank you! So, initially I had converted the original dataset into a csv. Yes the sites were predefined as Low and High aridity based upon their geographical location and the humidity present.

**Comment by KaranSingh-14** [comment]
> Great presentation! The plot you generated is clear and easy to interpret. I also think it would be beneficial to assess the statistical significance of your data and possibly use geom_errorbar() to add error bars to your plot. If you decide to add error bars, you may want to select a different color for your bars.

Thank you for the feedback! I will look into using the geom_errorbar(), as I believe it would further strengthen my data conclusions. I was actually thinking of a way to convey the statistical significance, so this will help a lot!

**Comment by KaranSingh-14** [comment]
> Interesting find that there is higher biodiversity found in areas of low aridity. Future studies could perhaps uncover potential factors that play a role in why biodiversity changes with different conditions; this could then be useful in future conservation projects, especially when determining what species would fare best in diff temperatures (since climate change is a very pressing issue currently).

This is great feedback and I completely agree with you, we definitely need to further this type of research and figure out a way to have conservation of species. Climate change is a concerning issue,  and it may even lead to some species going extinct, because they are not equipped to handle the higher temperature.

**Comment by KaranSingh-14** [comment]
> Awesome job! Your visualizations very clearly showed the trend you were describing. Have you tried testing if the differences in coexistence values across dry versus arid sites were statistically significant? If so, what tool(s) did you use? For my data, I ran a one-way ANOVA with several variables using scipy.stats, which would be applicable here.

Thank you! I have not tested among the dry sites to see if they statistically significant, but I will definitely look into ANOVA and the variable spicy.stats in order to get more conclusive and possibly statistically significant results for my dataset.

**Comment by Deap-Bhandal** [comment]
The presentation was easy to follow and was visually appealing. I did have a question on your analysis on coexistence. Specifically, did the dataset you used delve into whether species coexisting had facilitative or competitive relationships. I was just curious if the aridity level had anything to do with that. Overall, nicely done.

**Comment by KaranSingh-14** [comment]
> The presentation was easy to follow and was visually appealing. I did have a question on your analysis on coexistence. Specifically, did the dataset you used delve into whether species coexisting had facilitative or competitive relationships. I was just curious if the aridity level had anything to do with that. Overall, nicely done.

Great question Deap! The article specifically did not mention if the interactions were positive or negative. I know that it has to be one or the other based upon the Plant Ecology class I took last quarter. I believe stress plays a huge role as well and maybe I can delve deeper into that part of it in any future projects!

**Comment by soniavsd** [comment]
Really interesting find that low aridity has higher levels of biodiversity! Do you think this only applies to Mediterranean ecosystems, or with any? If its only Mediterranean, what features about it makes it like this??? Great presentation overall!

**Comment by goharmihranian** [comment]
Hi Karan! Great presentation! Agreeing with everyone else, I am extremely surprised that low aridity has higher levels of biodiversity. Especially since I just took a class about soil and arid soils are supposed to support the most amount of biodiversity. Going off of what Sonia said, I definitely think it will vary between ecosystems because each ecosystem has a different set of microbes that support the soil and allow for plant growth. Great job!
