### ISSUE TITLE
Linh Ngau Lightning Presentation

### ISSUE THREAD

**Issue by LinhN16** [ShawnTylerSchwartz/eeb-c177-w20#69]
This is the link to my lightning presentation. Sorry for the stuttering. and the lightning speed of talking. Thank you and good luck with finals!

https://youtu.be/j-7AmgJs-nc

**Comment by alexphu1230** [comment]
Great job Linh! I enjoyed your presentation! I really liked seeing the visualization of the correlation between each of your health measures! I wonder, if compared to another subset of patient data comparing the same health measures, would the correlations still hold (showing that the correlations are representative of the population as a whole and not a subset sample)? Great job!

**Comment by jessicadeanda** [comment]
The topic you chose is really interesting! I really like that you compared age groups given the population demographic you reviewed. If you could find a dataset reporting the prevalence of diabetes over time (for example, over the span of 10 years) it would be interesting to visualize any existing trends. Overall, great presentation!

**Comment by jpocon** [comment]
Hi Linh, really enjoyed learning about your work! Have you thought about plotting one half of the correlation matrix for better readability? Also, does your code output the models into saveable files?

**Comment by haonguyen318** [comment]
Hi Linh! I really enjoyed listening to your project, especially hearing about the topic that you chose and why you chose to use that data. I've have never heard of The Prima so it was very interesting to hear you explain who they are and what kind of data collection to chose to analyze from their group. Your correlation plot also gave a good visualization on how big of an effect diabetes have on this group of people. Also I liked how you walked us through your code on R and it was very detailed. Your explanation of your code demonstration was also very easy to understand. Great job on the presentation!

**Comment by LinhN16** [comment]
> Great job Linh! I enjoyed your presentation! I really liked seeing the visualization of the correlation between each of your health measures! I wonder, if compared to another subset of patient data comparing the same health measures, would the correlations still hold (showing that the correlations are representative of the population as a whole and not a subset sample)? Great job!

Thanks for the feedback, Alex! I think that would be a good future study / analysis to make because it would be a basis for determining whether type 2 diabetes affects other populations differently, since genetics may also play a role as well.

**Comment by motazb** [comment]
Hey Linh! I think your presentation is great for studying this population of Native Americans. It definitely is a lightning presentation, but I did catch what you were trying to do. I wonder, how would you do the experiment and account for the fact that the data is skewed since the older population is very little compared to the younger population? Either way, interesting study. Good job!

**Comment by chausteven** [comment]
Hey Linh, I thought your presentation was very informative and that your code allowed you to extract really detailed statistics like significant code and R-squared values. I was wondering if you created a function or used a specific module that allowed you to display all these statistical data in a very organized manner? Also, how did that function or module work to calculate all those statistical values?
