### ISSUE TITLE
Cloning Repositories 

### ISSUE THREAD

**Issue by fridalejandra** [ShawnTylerSchwartz/eeb-c177-w20#7]
Hey y'all
I have not been able to clone the repository. In my many attempts I tried restarting ubuntu and not sure what happened, but I cannot get back to the desktop.

It now looks something like this. 
![Screen Shot 2020-01-11 at 5 54 00 PM](https://user-images.githubusercontent.com/59626252/72213059-fea52600-349c-11ea-8925-5ff5949ca5da.png)

I was wondering if 
1. anyone had problems cloning? 
2. how to get back to the desktop interface of ubuntu?

thanks!

**Comment by shawntz** [comment]
Hi @fridalejandra two questions:

1. When you are attempting to clone the repository, what exactly are you typing? Remember that if you are simply copy-and-pasting what I wrote in the lab manual for Week 1, it will not work. You need to replace the `username` portion of the URL with your GitHub username, and the `repository.git` portion with the name of the repository that you created on your own GitHub account. After looking at your profile, I see you have one repository created named `fifi`. Can you make a new repository named something along the lines of `eeb-c234-homework` on GitHub and then use that name when you try to clone (i.e., `eeb-c234-homework.git`)? Let me know what happens. This should be the repository you use for assignments for this class.

2. Be careful when turning the virtual machine on and off freely. Treat it as if you'd treat a physical computer and hardware, and make sure you shut it down properly each time: by going to the power off mode in Ubuntu as you would similarly do on your host operating system (MacOS, Windows, etc.). Try turning off your laptop and rebooting it and then reopening a fresh session of VirtualBox and see if that solves your problem.
