### ISSUE TITLE
Omer Lavian Junco Lightning Talk

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#70]
[My Lightning Talk](https://www.youtube.com/watch?v=6JCHjdwmmHc)

Seeing other people's presentations I realized that I neglected to add a github link to my presentation, so here it is:
https://github.com/omerlavian20/eeb-c177-project

**Comment by jpocon** [comment]
Hi Omer, wonderful talk! I learned something new (Euclidian FIDs)! When you ran through your demo and printed both the stat variables (p-vals, etc.) as well as the plots, do you capture these outputs in a file format like .csv or .txt?

**Comment by omerlavian20** [comment]
> Hi Omer, wonderful talk! I learned something new (Euclidian FIDs)! When you ran through your demo and printed both the stat variables (p-vals, etc.) as well as the plots, do you capture these outputs in a file format like .csv or .txt?

I did not, but I could probably add that feature (I don't know how I could add the plots, though.). Thanks for the suggestion!

**Comment by soniavsd** [comment]
Really good presentation Omer! It's incredibly impressive that you were able to find a significant difference in your data! I also really like the overall topic of how the effects of human society have effects on the natural world in ways we have not thought possible. Great work!

**Comment by omerlavian20** [comment]
> Really good presentation Omer! It's incredibly impressive that you were able to find a significant difference in your data! I also really like the overall topic of how the effects of human society have effects on the natural world in ways we have not thought possible. Great work!

Glad you enjoyed it! I will say that this data had been analyzed before this by a grad student in the lab this comes from, but I wrote all the code for this analysis on my own. I'd heard that urban versus native had a significant difference before from talking to someone from the lab. Based on the plot and correlation coefficient for initial distance vs. Euc FID, I was not expecting there to be a significant correlation, so seeing the p-value for that was pretty cool (Though there is previous research supporting that relationship so I guess it's not THAT surprising.).

**Comment by jessicadeanda** [comment]
Great findings! I think your evaluation of the statistical significance of your results really strengthens your argument. I was surprised to see that you imported your dataset as an excel file instead of a csv file! Did you import the entire dataset, or just a few selected columns based on the header name?

**Comment by omerlavian20** [comment]
@jessicadeanda I imported the whole excel file using pandas for the function I demoed. When I looked at categorical variables I used the shell to make individual csv files with the Euclidian FID values for each category and then brought those files in using with open() as.

**Comment by shreyatrivedi26** [comment]
Awesome work Omer! I really liked the idea of your presentation. It made me learn something new and interesting. 
Wanted to know if you explored the statistical visualizations like a boxplot in Python too? Conversely, did you try the correlation coefficient analysis in R too the way you did it in Python? 
Which software did them better?

**Comment by omerlavian20** [comment]
> Awesome work Omer! I really liked the idea of your presentation. It made me learn something new and interesting.
> Wanted to know if you explored the statistical visualizations like a boxplot in Python too? Conversely, did you try the correlation coefficient analysis in R too the way you did it in Python?
> Which software did them better?

Good questions! I tried neither of those things, but I would like to in the future. Since R was made for stats I feel like the stats would be pretty convenient to do in R. As for boxplots in Python, I do not know how hard those would be in Python, though the plots in Python look really cool. When I saw the plots that someone in this class did in Python (It was for a project on animal behavior.) I was STUNNED, so I would definitely like to explore that in the future.

**Comment by fridalejandra** [comment]
Omer, love the Dark-Eyed Junco shots on the intro slide. The 'multiple_corrs_excel' function seems extremely efficient. From the outputs of this function, did you then run the correlations in R for aesthetic purposes? What if you used the 'Seaborn' package in python on the outputs you got from 'multiple_corrs_excel', would this be a possibility? 
Very clean code by the way !

**Comment by WhitneyTsaiNakashima** [comment]
Cool work! I thought you explained each of the variables really well and this made your presentation easy to follow. It would be cool to use this code to explore other relationships in this system. Does the data set have other variables that you could use this code to analyze?

**Comment by omerlavian20** [comment]
> Omer, love the Dark-Eyed Junco shots on the intro slide. The 'multiple_corrs_excel' function seems extremely efficient. From the outputs of this function, did you then run the correlations in R for aesthetic purposes? What if you used the 'Seaborn' package in python on the outputs you got from 'multiple_corrs_excel', would this be a possibility?
> Very clean code by the way !

If I were to expand this work I would definitely explore both doing the correlations in R and the seaborn package. I plan on using what I've learned in this class in the future so I will definitely consider your suggestions. Thank you!

**Comment by omerlavian20** [comment]
> Cool work! I thought you explained each of the variables really well and this made your presentation easy to follow. It would be cool to use this code to explore other relationships in this system. Does the data set have other variables that you could use this code to analyze?

There are other variables I could test. I wrote another set of functions to test categorical variables, and I could use multiple_corrs_excel to look at some of the other interval variables in the dataset. For this project I compared all the variables that are related to urbanization that could have an effect on FID.

Glad you enjoyed the project!

**Comment by goharmihranian** [comment]
Hi Omer! I really enjoyed how well thought-out and organized your presentation was. The data was very interesting and cool to learn about as well. Your presentation was super easy to follow and very clean! Awesome job
