### ISSUE TITLE
Deap Singh Bhandal Lightning Presentation

### ISSUE THREAD

**Issue by Deap-Bhandal** [ShawnTylerSchwartz/eeb-c177-w20#71]
Below is the YouTube link for my Lightning Presentation:
https://youtu.be/NmYewaoJzZs

**Comment by LinhN16** [comment]
Super cool analysis using the overlay of plots, Deap! I took a course last quarter regarding Plant Ecology and it was super interesting hearing your take on the fact that trees will migrate to northern areas in response to climate change. Your code would be especially useful to compare how trees in areas spanning the world are responding to climate change and perhaps aid in conservation efforts.

**Comment by jessicadeanda** [comment]
Wow your presentation as a whole is clear, concise, and extremely visually appealing! This is beyond the scope of this class, but it would be really great to see a map of the northern migration of these tree species if you are able to use GIS. I also think it would be beneficial to incorporate temperature data over the past few decades to plot migration VS change in temperature using R.

**Comment by shreyatrivedi26** [comment]
Good Job! 
Very well explained. I really liked the way you have organized your slides and the content on it. It is tidy and very easy to understand.
It found you analysis very interesting particularly because I am also trying to study the variabilities in a particular variable and it would be great to know what are the other variability analyses you are planning to include as the part of your project?
Do you think box plots are the best when it comes to studying variations? Do you think they have a better alternative which is more user-friendly?
I ask this because they used to confuse me a lot initially. :P

**Comment by KaranSingh-14** [comment]
First of all, I would like to say this is great presentation Deap.  I have a couple of questions for you. 1) What exactly did you mean by obstacles in the species migration pattern as the climate warms? From what I understood, it appears that the obstacles are more towards physical geographical restrictions such as mountains, oceans, etc. as opposed to some genetic component. 2) Also, I was wondering if you would be able to plot species and the type of environment these species were found in to have any correlation. Maybe Species abundance and the degree of stress present in the environment could be plotted against one another to possibly see another trend that could explain the migration pattern. Lastly, do you think a histogram that counts the number of species and reveals its location will make the data even more clear from a visual perspective?

**Comment by robertreny** [comment]
Great job @Deap-Bhandal, the presentation style was super cool in and of itself and you had a great overall information flow. You walked through the code really well and the final box + jitter plot really effectively shows your result.

**Comment by motazb** [comment]
Hey Deap! I think this was a really cool idea for your project. The representation of the data you chose is also excellent. However, I do wonder, why would some species of trees be more susceptible to longitudinal change than they would be to latitudinal change or vice versa? I would imagine that if a species of trees isn't adaptive, it wouldn't be adaptive to longitudinal or latitudinal change, not more towards one way or the other. And your plot does show that they are consistent for the most part but I wonder if they aren't perfectly consistent because of analyzation error or if it's because it does make some slight difference in the environment between longitudinal and latitudinal change. Anyways, awesome job with the project. It brings up very interesting questions.

**Comment by Deap-Bhandal** [comment]
> Super cool analysis using the overlay of plots, Deap! I took a course last quarter regarding Plant Ecology and it was super interesting hearing your take on the fact that trees will migrate to northern areas in response to climate change. Your code would be especially useful to compare how trees in areas spanning the world are responding to climate change and perhaps aid in conservation efforts.

Oh I took that class last quarter as well (161 with Kraft)! That class did inspire me to relate my analysis to tree migration in response to climate change. Although my dataset only included Live Oaks in North America, I would have liked to analyze several tree species spanning the globe.

**Comment by Deap-Bhandal** [comment]
> Wow your presentation as a whole is clear, concise, and extremely visually appealing! This is beyond the scope of this class, but it would be really great to see a map of the northern migration of these tree species if you are able to use GIS. I also think it would be beneficial to incorporate temperature data over the past few decades to plot migration VS change in temperature using R.

Thanks so much! Yeah it occurred to me later that GIS might have been a better way to portray my data. My dataset did have temperature data, but it did not span decades. I agree if it included that, it would have been much more interesting to analyze. I also agree that relating the migration back to temperature would have been a good idea.

**Comment by Deap-Bhandal** [comment]
> Good Job!
> Very well explained. I really liked the way you have organized your slides and the content on it. It is tidy and very easy to understand.
> It found you analysis very interesting particularly because I am also trying to study the variabilities in a particular variable and it would be great to know what are the other variability analyses you are planning to include as the part of your project?
> Do you think box plots are the best when it comes to studying variations? Do you think they have a better alternative which is more user-friendly?
> I ask this because they used to confuse me a lot initially. :P

Thank you! In addition to seeing the variability of latitudes and longitudes, I would like to see any variability of climate data between trees of the same species. I agree that box plots are not the best when it comes to studying variation. I'm just not familiar with all the other packages in R that would have been better to analyze variance. I would have much rather used a package like the one you used in your presentation.

**Comment by Deap-Bhandal** [comment]
> First of all, I would like to say this is great presentation Deap. I have a couple of questions for you. 1) What exactly did you mean by obstacles in the species migration pattern as the climate warms? From what I understood, it appears that the obstacles are more towards physical geographical restrictions such as mountains, oceans, etc. as opposed to some genetic component. 2) Also, I was wondering if you would be able to plot species and the type of environment these species were found in to have any correlation. Maybe Species abundance and the degree of stress present in the environment could be plotted against one another to possibly see another trend that could explain the migration pattern. Lastly, do you think a histogram that counts the number of species and reveals its location will make the data even more clear from a visual perspective?

Thank you! Yes, by obstacles I meant geographical restrictions. Genetic components could be obstacles, but since individuals from the same species are likely to share these as well, they would likely impact most colonies of that species. I did plot specific morphological characteristics vs climate data, but I would like to plot species vs. environment as well as you proposed. Also, I agree that a box plot is not the best to show variance. A histogram could work to but if you're proposing multidimensional data (species, count, and location), I think I could use a plot overlaid on a map showing species count while simultaneously showing location.

**Comment by Deap-Bhandal** [comment]
> Great job @Deap-Bhandal, the presentation style was super cool in and of itself and you had a great overall information flow. You walked through the code really well and the final box + jitter plot really effectively shows your result.

Thank you so much! The boxplot overlaid on the jitter plot was the best way I knew at the time how to represent the variance in R. However, as other students have mentioned, I could have used a plot overlaid on a map for a more clear visual appearance. But, I'm glad you did not have any problems in interpreting my graphs.

**Comment by Deap-Bhandal** [comment]
> Hey Deap! I think this was a really cool idea for your project. The representation of the data you chose is also excellent. However, I do wonder, why would some species of trees be more susceptible to longitudinal change than they would be to latitudinal change or vice versa? I would imagine that if a species of trees isn't adaptive, it wouldn't be adaptive to longitudinal or latitudinal change, not more towards one way or the other. And your plot does show that they are consistent for the most part but I wonder if they aren't perfectly consistent because of analyzation error or if it's because it does make some slight difference in the environment between longitudinal and latitudinal change. Anyways, awesome job with the project. It brings up very interesting questions.

Thank you! The analysis I did so far is not conclusive to say which species are more susceptible to longitudinal change or latitudinal change. I mostly wanted to see where tree species are currently located so see which have the most chances of either adapting to new climate conditions or migrating Northward. Since climate varies more when changing latitude than longitude, trees that have a high variance of latitude show they are able to adapt to a wider range of temperatures. There are however, factors I did not consider such as changes in elevation. Yes, most species do tend to cluster around certain areas, but some do have more spread out clusters. If the clusters are spread out latitudinally, that shows a possibility they can adapt to more environments. However, variance across longitudes only shows a higher chance of being able to migrate North when they have to. I understand that might not be the most clear so let me know if you have follow up questions.

**Comment by goharmihranian** [comment]
Hi Deap! Awesome presentation! I really enjoyed your plots that you created, they were very clear and great representations of the data! I very much appreciated how you walked us through the plot-making process. Great work!

**Comment by Deap-Bhandal** [comment]
> Hi Deap! Awesome presentation! I really enjoyed your plots that you created, they were very clear and great representations of the data! I very much appreciated how you walked us through the plot-making process. Great work!

Thank you so much! I’m glad you enjoyed the presentation and didn’t have much trouble interpreting the data.
