### ISSUE TITLE
Steven Chau - Lightning Presentation

### ISSUE THREAD

**Issue by chausteven** [ShawnTylerSchwartz/eeb-c177-w20#72]
Lightning Presentation on Anti-Predator Behavior:
https://youtu.be/Kv_rEQQS2Gk

**Comment by omerlavian20** [comment]
Awesome job! I really like that you used the input() function as opposed to just placing the variables in the def() statement. I kind of wish I did that in my code to be honest. It can be a bit unnerving at times to have to write a whole bunch of arguments within parentheses as opposed to putting in each thing separately with input().

**Comment by LinhN16** [comment]
I agree with Omer in that using the input() was a super creative way to actively demonstrate your code! The analysis was super interesting too, as I could relate it to material that I took in an EEB class on animal behavior that covered material about predator- prey interactions. These experiments make me wonder how we are changing species interactions (is this good or bad?) by exposing preys to predators so that they no longer react.

**Comment by goharmihranian** [comment]
I agree with Omer and Linh that the input option was a great idea. I had originally done that for my project in Python as well but I didn't really know how to after I switched to R, although it would have been helpful. Did you do your plots in R and somehow have them print out in Python or were they generated through Python originally? Awesome project!

**Comment by alexphu1230** [comment]
Hi Steven! I thought it was so cool that you had an interactive input option in your code! It made everything so streamlined and I thought the graphs you put at the end of your script gave a lot of valuable information! Great job!

**Comment by haonguyen318** [comment]
I really enjoyed the topic that you chose for your project! I liked that your motivation for this project was species conservation and endangered species. It is indeed a very important subject that needs more research and discussion. Your coding demonstration was very easy to follow along and I like how you walked us step by step on how you generated your plots. It's also interesting to see how different variables affect the Bettongs' flight initiation. Overall great job Steven!

**Comment by WhitneyTsaiNakashima** [comment]
Great job! You explained and walked us through your code very clearly and I liked the data visualizations. It is cool that the data showed the Bettongs are learning and adjusting their behavior to different variables. What other variables did you analyze on your last slide and are there other systems that you might be interested in exploring using this code?

**Comment by motazb** [comment]
Hey Steven! These are some really nice graphs. I would suggest when prompted with which csv file to analyze, add options so that the user knows which files are available. I would probably also just make maybe make those two separate functions since putting it all in one function seems super compact and would suck if an error popped up. Otherwise, again, I do like those plots a lot. I think they were a great choice for this set of data you used.

**Comment by chausteven** [comment]
> I agree with Omer in that using the input() was a super creative way to actively demonstrate your code! The analysis was super interesting too, as I could relate it to material that I took in an EEB class on animal behavior that covered material about predator- prey interactions. These experiments make me wonder how we are changing species interactions (is this good or bad?) by exposing preys to predators so that they no longer react.

I think looking into species interaction is a necessary step into species conservation since it allows us to understand what it takes for these species (usually endangered) to thrive in an ecosystem. For the experiment I took the data from, the Bettongs are actually preys of feral cats, so there are no artificial changing of species interaction!

**Comment by chausteven** [comment]
> I agree with Omer and Linh that the input option was a great idea. I had originally done that for my project in Python as well but I didn't really know how to after I switched to R, although it would have been helpful. Did you do your plots in R and somehow have them print out in Python or were they generated through Python originally? Awesome project!

I actually used seaborn which is another plotting module that is built upon matplotlib. It functions similarly to matplotlib, but allows me to create nicer graphs that look similar to the graphs created on ggplot2.

**Comment by chausteven** [comment]
> Awesome job! I really like that you used the input() function as opposed to just placing the variables in the def() statement. I kind of wish I did that in my code to be honest. It can be a bit unnerving at times to have to write a whole bunch of arguments within parentheses as opposed to putting in each thing separately with input().

Thank you Omer!!

**Comment by chausteven** [comment]
> Hi Steven! I thought it was so cool that you had an interactive input option in your code! It made everything so streamlined and I thought the graphs you put at the end of your script gave a lot of valuable information! Great job!

Thank you Alex!

**Comment by chausteven** [comment]
> Great job! You explained and walked us through your code very clearly and I liked the data visualizations. It is cool that the data showed the Bettongs are learning and adjusting their behavior to different variables. What other variables did you analyze on your last slide and are there other systems that you might be interested in exploring using this code?

Thank you Whitney! The two graphs on the top were looking at how foraging and vigilance (other behavior traits) changed over time in Bettongs exposed to predators and those that were not. The graph at the bottom of the slide was looking at how sex affected the Bettongs flight initiation distance. As for other systems, I want to explore how urbanization is affecting these predator-prey relationships and how we as a society are affecting anti-predator behavior in species.

**Comment by chausteven** [comment]
> Hey Steven! These are some really nice graphs. I would suggest when prompted with which csv file to analyze, add options so that the user knows which files are available. I would probably also just make maybe make those two separate functions since putting it all in one function seems super compact and would suck if an error popped up. Otherwise, again, I do like those plots a lot. I think they were a great choice for this set of data you used.

Thank you Motaz! These are great suggestions, especially the one displaying which files are available to use! I actually had the function separated when I initially started the project, but I think you are right that having separate functions would make it easier to debug and fix when needed.
