### ISSUE TITLE
Gohar Mihranian- Lightning Presentation

### ISSUE THREAD

**Issue by goharmihranian** [ShawnTylerSchwartz/eeb-c177-w20#74]
[Presentation](https://www.youtube.com/watch?v=fntPcrvmyvM)

[Github link](https://github.com/goharmihranian/eeb-c177-project)

**Comment by omerlavian20** [comment]
Super cool project! I love that you used what you learned in this class to make your life in lab easier. From the presentation it is very clear that you found R very helpful in your project, but how (if at all) of you use Python? Was Python a tool you used to clean your data before plotting it?

**Comment by goharmihranian** [comment]
@omerlavian20, Thank you! So I initially started doing this in Python but Python was giving me some issues with separating the data (making them integers separated by a comma). So Shawn suggested we try it in R and it took so much less time to do it in R and cleaned up the data much better than Python! So I scratched everything I did on Python and redid it in R.

**Comment by altaing** [comment]
Hello, really cool project! Was it that your code made a different plot for every single parameter in your dataset? Would it be possible for your code to just give you one specific plot (using only two specified parameters)? And you said you made this for your lab, correct? Do you think you will continue using this function or similar functions to this in the future for your research?

**Comment by jpocon** [comment]
Hi Gohar, great presentation. Loved how you were able to take such an interesting and complex process with an unfamiliar datasource (at least from my persepective) and help digest it for your audience in the time alotted! I noticed in your reply to Omer that you scrapped all your Python code and moved to R. Have you explored other visualizations for your data in ggplot? Or thought of plotting multiple files in one plot and color coding? Thanks!

**Comment by goharmihranian** [comment]
@altaing, so this dataset is a little bit complicated and I did it in the way my lab wants it. So each run that you saw in that folder is a list of numbers. The numbers represent the heart rate of the pig during an intervention. So Run1 might be an IVC occlusion, Run2 might be 4Hz Vagus stim, Run3-8Hz vagus stim or aortic occlusion. So when I input the data into the ScalDyn program, it calculates the integrals of the QRS wave, which represents the activation time of the HR, and of the T wave, which represents the recovery time of the heart rate. When you subtract the RT from the AT, you get the Activation Recovery Interval(ARI). And so I would only plot one run at a time to see how that particular intervention affected the heart rate. In the example plot I showed you, we saw that the heart rate decreased from baseline and then slowly started climbing back up.

I will definitely continue using this function because it will save me so much time. Like I said in the presentation, this takes 10 seconds for an entire file; when before I was spending 3 minutes per run within a file.

@jpocon, Hi Jon! Thank you! So I haven't really explored ggplot for this because I don't need to. I just need a simple scatterplot for each run, as I mentioned in my response to Alton. All I need to see for the purposes of this research is that increase or decrease in HR. I would have loved to plot cool things but it really wasn't necessary for my project so I didn't. I loved looking at everyone else's really cool plots, though!

**Comment by haonguyen318** [comment]
Hi Gohar! Hearing the process that it took you to compile your data onto an excel sheet was very interesting and I commend you for taking the time to do that. It sounds like a very tedious and long process but I'm glad that you were able to use data directly from your lab project. Your code demonstration on R was very clear and it is easy to understand how you generated a scatterplot using your code. Overall great job on your presentation!

**Comment by estmendoza** [comment]
Hi Gohar! I really enjoyed hearing how practical the code you created works for you! The fact that your code works for all the files in your folder and not just one at a time is really impressive. If you get a new file will your program generate a new pdf for that specific file only, or will it create new pdfs for the other files as well?

**Comment by motazb** [comment]
Hey Gohar. Amazing job with your project. You were able to produce readable graphs from your super complicated set of data, and I'm sure that was intense. Great presentation as well!

**Comment by dylanreadel** [comment]
It's great to see that you made an excellent use of this course by making your lab experience more efficient. Does the code have to be in a very specific format for this code to work and produce the plots, or is it modular/generalizable so that many datasets with slight variations can be input?

**Comment by goharmihranian** [comment]
@haonguyen318 Thank you!

@estmendoza, Thank you! So if you take a look at the very beginning of my code, theres a variable called "pigfolder" and in this case I have it set to the name of the folder I wanted to do it for. When I get data from a new pig, all I have to do is change what that variable is set to and it'll do it for that file as well!

@motazb Thank you, Motaz!

@dylanreadel, so because the data sets were so complicated from the beginning, they had to be split in a very particular way for the code to work.
