### ISSUE TITLE
Dylan Readel - Lightning Presentation

### ISSUE THREAD

**Issue by dylanreadel** [ShawnTylerSchwartz/eeb-c177-w20#75]
[Approaching Conservation Through Code](https://youtu.be/FgbKPYPjrY0)

**Comment by omerlavian20** [comment]
This was super cool! "Conservation Through Code" is a sweet project name. I love reptiles and birds, so it was cool to see them featured in this project! Something I've been thinking about doing myself was using iNaturalist data to determine the best times to go find different animals in the wild (I might use a histogram or a density graph from ggplot to do this.). I like that you, like several other people in the class, placed data onto maps using R. That is a feature I definitely want to explore in the future!

**Comment by LinhN16** [comment]
This was super creative, Dylan! This could definitely be a useful tool for future conservation projects, perhaps using it to visualize data over time (to record how fluctuations in populations change over time to simulate more natural environments).  Omer's comment on using iNaturalist data to determine best times to see different species would be a cool concept to explore with coding as well.

**Comment by goharmihranian** [comment]
Super cool project, Dylan! I think its really cool that you manipulated data from reptiles and birds in the LA county. I like that you used grep command to implement regular expressions into your code, exemplifying and putting into fruition what we've learned in class.  How did you figure out ggplot2 had that mapping option? Did you have to convert your dataset into a dataframe so ggplot would graph it, because I know I ran into those sorts of complications with my dataset?

**Comment by altaing** [comment]
Wow those are some really cool plots that you created! I think it's really important to monitor the biodiversity of areas overtime as it can be a good indicator how the environment is changing. In this sense, your code can be a powerful tool in conservation as it can definitely be applied to see find any shifts in species when using data from different time points. You said you used ggplot and R, but how much of this did you manage to do in Python?

**Comment by jpocon** [comment]
Loved the presentation Dylan! Forgive me if I missed this in your talk, but did you map all iNaturalist data or only the research-grade observations? Also, the ggplot maps package is great, but wanted to share some unsolicited advice for mapping in R. If you are interested in making other maps in R, check out the tmap/leaflet packages -- if you don't already know about these -- there are options for interactive map making with just a few lines of code and they play very nicely with the tidyverse: https://geocompr.robinlovelace.net/adv-map.html

**Comment by fridalejandra** [comment]
Hey Dylan, great presentation. I like Omer, love birds and reptiles. I know about iNaturalist but have yet to use it. Did you download this data as a csv ? Is there an export tool or did you scrape this data?

**Comment by haonguyen318** [comment]
Hi Dylan! I liked how you explained your motivations for choosing this data for your project. It was also very interesting how you created a map plot using R and ggplot. I wasn't aware of the map package from ggplot 2. I think I will be using this package for my code as well. Overall great job on your presentation!

**Comment by estmendoza** [comment]
Hi Dylan! I'm impressed by your usage of the mapping package along with the plotted species points. I like how you demonstrated your program with two different types of animals. How were you able to specify what region of the map you wanted to show? Or how did you know the boundaries of the points within your dataset?

**Comment by dylanreadel** [comment]
@goharmihranian I figured out the mapping functions in ggplot2 through a lot of googling actually. I downloaded data directly from iNaturalist, imported it to my R script as a CSV, and plotted the given latitude and longitude using the "geompoint" feature. There are, however, several different ways to plot location points in R!

@altaing I actually only did the mapping in R. I did do other analyses in Python. I wrote a script that extracts species occurrence dates from iNaturalist data and plots a graph visualizing the spread of species occurrences throughout the seasons. This is available on my GitHub, as well.

@jpocon I chose to only map research-grade observations since they are reviewed and accurate. Thanks for letting me know about these packages, I'll have to check them out!

@fridalejandra I downloaded occurrence data directly from iNaturalist as CSV files. It's extremely easy to work with and you can choose what columns you would like to download directly on iNaturalist.

@estmendoza ggplot2 gives the user the ability to set the coordinate boundaries using the following code `coord_cartesian(xlim = c(-118.9, -117.9), ylim = c(33.6, 34.6))`. These are the coordinates I chose to use to encapsulate just the LA River Watershed. Furthermore, within the theme parameters for the map, I used the line `theme(aspect.ratio = 1)` to make sure the map always came out as a square and did not get stretched.

**Comment by soniavsd** [comment]
Really good presentation Dylan! Ive used iNaturalist before on previous expeditions, but I had no idea that there was feature to download data on any organism you want, that's honestly so cool! Is there a feature on ggplot that allows you to overlap a bird and reptile species map? I think it would be an interesting study to view how two different species intersect.
