### ISSUE TITLE
Whitney - Mapping Yellow Warbler Samples in R

### ISSUE THREAD

**Issue by WhitneyTsaiNakashima** [ShawnTylerSchwartz/eeb-c177-w20#76]
https://youtu.be/R-oVcohJ0Z4

**Comment by jpocon** [comment]
Hi Whitney, loved the presentation. As a geographer, I got giddy seeing more maps! My question for you is, did you make the map legend ("tissue" "extraction" "specimen") using the ggplot/ggmap commands?

Also, completely unsolicited advice here, but if you are interested in making your maps in R, check out the tmap/leaflet packages -- if you don't already know about these -- there are options for interactive map making with just a few lines of code and they play very nicely with the tidyverse: https://geocompr.robinlovelace.net/adv-map.html

**Comment by omerlavian20** [comment]
This was super cool! I liked the presentation both for the content and because you made what you did pretty easy to understand. You mentioned that you isolated columns using R. I was wondering how you did that. For my project any time I had to isolate specific sections of my dataset I either went into Excel in a GUI and copied the relevant data or used the shell to isolate specific values I needed. I'm curious if your methodology might have let me do what I wanted to do more efficiently...

**Comment by soniavsd** [comment]
Hey Whitney! Great organization in your presentation! I really like the cross sectional applications of your approach to your research. I can really see how this method of analysis can be used for other topics and not just warblers! I am also curious as to what the next steps in your research be and how you might use this data in the future!

**Comment by fridalejandra** [comment]
Hi Whitney! The map is stunning. As someone who has used GIS softwares to make maps I have recently come across making maps in R and am surprised at the feasibility. For the Riparian habitats, was this also its own shape file and did you find the longitude and latitude of your samples corresponded to the CA shape file without any problems?  (I often have projection issues so I was curious)

**Comment by robertreny** [comment]
Great job Whitney! Your final product looks really great. Your coding was very clear and visually well-organized. I am interested in hearing what the mapping and data might be used for in the future and I was also wondering what tutorial you used to learn your mapping?

**Comment by haonguyen318** [comment]
Hi Whitney! I really like how you mapped out your samples across California using R. It is also very impressive that you learned a new code from R by searching up tutorials on how to do a map plot. After seeing your map plot, I'm also motivated to do a map plot for my project to show a better visualization of my data. Overall great job on your presentation!

**Comment by WhitneyTsaiNakashima** [comment]
@jpocon  I actually wasn't able to make the map legend in ggplot. I had tried a few ways to include it for the presentation, but the way I separated my csv files for each sample type made it difficult. I think if I organize my data into a single csv file and access the data that way it, making the legend would be easier. Also, thanks for the resource, I will definitely look into it!

**Comment by WhitneyTsaiNakashima** [comment]
@omerlavian20 I used tidyverse commands to do this. I often download data from museum websites with many columns that I am often not interested in. It helps to have this code so that I can pull the same columns of data from files with the same structure really quickly. I will be updating my repository later this week, so check back if you're interested in specific code!

**Comment by WhitneyTsaiNakashima** [comment]
@soniavsd I often need a way to quickly map genomic samples on a map so that I can ensure that I am sampling across my areas of interest. I am interested in population genomics and phylogenetic relationships in birds. Once I have these maps, I can choose samples depending on the scope of my study, process them in the lab, and send them for DNA sequencing. I will likely use this mapping data again for analyzing my DNA sequence data and for visualizing patterns. These visualizations are super important for presentations and publications to be able to communicate results of my study effectively.

**Comment by WhitneyTsaiNakashima** [comment]
@fridalejandra Unfortunately, I did not have access to the raw data for the riparian habitat. If I had found the base map earlier, I may have been able to reach out to PRBO to get the raw data. I did have some issues with overlaying the points onto the base map. For this map, I did not need the points to be precisely on the localities, I just needed approximate regions. For future, more accurate maps, I would definitely recommend getting raw data and incorporating all the layers in R.

**Comment by WhitneyTsaiNakashima** [comment]
@robertreny Here's the tutorial I followed! https://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html

**Comment by goharmihranian** [comment]
Hi Whitney, I thought it was so cool that you were able to map the samples of the Warblers on an actual outline of California! I never knew you could do that and I commend you for taking the time to figure it out! It was also very impressive that you were able to overlay your datapoints onto the big map! Awesome job!
