### ISSUE TITLE
Hao Nguyen - Lightning Presentation

### ISSUE THREAD

**Issue by haonguyen318** [ShawnTylerSchwartz/eeb-c177-w20#78]
Here is the YouTube link to my lightning presentation on climate change:
https://www.youtube.com/watch?v=Zfq4gdiCI3w

**Comment by soniavsd** [comment]
Hey Hao! I really liked your presentation. I really connected with your topic on climate change and how it is significant in modern society. Your linear regression graphs are very well done, and very easy to analyze with gradient colors and significant trends. My only critique would be to minimize the amount of words on the slides, especially the intro since it was hard to both listen to your explanations and read the descriptions. Great job overall!

**Comment by alexphu1230** [comment]
Hi Hao! I really enjoyed your presentation! I thought that it was a great idea to use visual representations for your data! It really helped break down the information of CO2 emissions! I thought it would be interesting if there was data to see how concentrated the emissions was, such as if it mostly came from one country or not? Again great job!

**Comment by chausteven** [comment]
Hi Hao, I noticed that you were able to create a data frame by uploading an excel file which was pretty cool and something I did not know you can even do. For my project, I also wanted to create a data frame but went about it using a module known as pandas. I was just wondering what module did you use and if it is different in any way from pandas?

**Comment by LinhN16** [comment]
Great presentation, Hao! I like how you thought of breaking the dataset down according to seasons; it was extremely helpful seeing that the temperature range for seasons differ, but what I found interesting was that they all had the same general trend. I'm sure that this kind of analysis would be helpful with navigating climate trends and seeing future predictions of climate change -- will it eventually plateau or will we see it climb further?

**Comment by estmendoza** [comment]
Hi Hao! I really liked your Linear Regression scatter plot and what that tells us about temperatures over the last 30 years. The color gradient was a nice touch! I also thought it was really creative how you isolated global temperatures by season and plotted them together. Did your dataset also include atmospheric levels of CO2 over the last 50 years? I think it could be interesting to see how that trend might compare with temperature levels?

**Comment by motazb** [comment]
Hey Hao! I thought your graphs were really cool. It's interesting to see the bar graph of greenhouse gases and how much more CO2 there is than everything else (although CH4 has a much bigger impact even at smaller amounts). I thought it would be interesting to see this by country. I think a visual representation of how much more carbon the U.S. emits than other nations would have also been cool. Also, a representation of the top countries' emissions graph over time and emissions rate of change graph over time would be very interesting. Of course, the U.S. would take the lead in emissions, but I would've been interested to see our emissions rate over time compared to other countries especially up to 2019, in which we were able to reduce our emissions a bit.
