### ISSUE TITLE
Jessica De Anda - Lightning Presentation

### ISSUE THREAD

**Issue by jessicadeanda** [ShawnTylerSchwartz/eeb-c177-w20#79]
https://youtu.be/tWxhynWhrpo

GitHub link: https://github.com/jessicadeanda/eeb-c177-project/blob/master/analyses/report/food-access.r

**Comment by jessicadeanda** [comment]
UPDATE: https://youtu.be/tWxhynWhrpo

**Comment by LinhN16** [comment]
Great analysis, Jessica! Your step-by-step demonstration through your code made it easy to understand how you constructed the final graph that was shown. It would be an interesting analysis to see the amount of fast food establishments that surround these communities, as this could potentially strengthen your argument.

**Comment by alexphu1230** [comment]
Great job Jessica! I really liked how you demonstrated the code and I think your insights into the code was really helpful! I think it would be interesting to look at the per capita income of each of your areas to see how you could quantify at which salary threshold controls at what point someone is in a food desert.

**Comment by shreyatrivedi26** [comment]
Good Job Jessica! 
It was a very nice demonstration of code. It showed how well you understood and followed each and every step which further made it easier for other watching it to follow. 
It was an interesting conclusion and my question is also related to that. 
How do you think the conclusion would change if you consider other factors as well such as the relative distance between the other stores in proximity, the income of the groups, the size of families and their preferences, etc. I believe if you consider these variables and then find a correlation, the conclusion would be a bit more robust. 
But as I said, it was a great talk!

**Comment by KaranSingh-14** [comment]
Great presentation! It was well articulated and easy to follow. I was just wondering you had done any p-value or other types of tests of significance to have a more definitive conclusion regarding your data set.  Also, I think the concept of food deserts, like this data is suggesting is a great way to raise awareness. Any suggestions on how to combat this issue?

**Comment by jessicadeanda** [comment]
> Great analysis, Jessica! Your step-by-step demonstration through your code made it easy to understand how you constructed the final graph that was shown. It would be an interesting analysis to see the amount of fast food establishments that surround these communities, as this could potentially strengthen your argument.

Thank you Linh! My dataset only reports information about income status, ethnicity, and vehicle access at each distance from the supermarket, but given that fast food plays such a major role in the prevalence of obesity within food deserts, I'll definitely try to find a supplemental dataset on this topic!

**Comment by jessicadeanda** [comment]
> Great job Jessica! I really liked how you demonstrated the code and I think your insights into the code was really helpful! I think it would be interesting to look at the per capita income of each of your areas to see how you could quantify at which salary threshold controls at what point someone is in a food desert.

Thank you for your suggestion, I think this is a great idea! Would you recommend displaying this data using a scatter plot?

**Comment by jessicadeanda** [comment]
> Good Job Jessica!
> It was a very nice demonstration of code. It showed how well you understood and followed each and every step which further made it easier for other watching it to follow.
> It was an interesting conclusion and my question is also related to that.
> How do you think the conclusion would change if you consider other factors as well such as the relative distance between the other stores in proximity, the income of the groups, the size of families and their preferences, etc. I believe if you consider these variables and then find a correlation, the conclusion would be a bit more robust.
> But as I said, it was a great talk!

Thank you Shreya! I am not sure if I understood correctly, but in terms of considering family size, I tried to account for varying population sizes per distance by calculating the percentage of the population that was flagged as low income. Do you mind clarifying what you mean by preferences as well? And yes, I agree that looking at income more quantitatively would strengthen my argument! Thank you again for these suggestions!

**Comment by jessicadeanda** [comment]
> Great presentation! It was well articulated and easy to follow. I was just wondering you had done any p-value or other types of tests of significance to have a more definitive conclusion regarding your data set. Also, I think the concept of food deserts, like this data is suggesting is a great way to raise awareness. Any suggestions on how to combat this issue?

Thank you Karan! I have not performed any significance tests yet, but I will definitely do that in R! From what I've read, we need MAJOR changes in the policies influencing our food system. The meat and dairy industries both play key roles in perpetuating food insecurity, so some papers suggest that instead of subsidizing cow feed, we should subsidize the production of fresh produce. If you are interested in reading about how the dairy industry (and the USDA) limits access to nutritious foods, I _highly_ recommend reading [The Unbearable Whiteness of Milk: Food Oppression and the USDA](https://www.law.uci.edu/lawreview/vol3/no4/Freeman.pdf). On a smaller scale, community gardens may make fresh produce more accessible within food deserts.

**Comment by robertreny** [comment]
Great job @jessicadeanda, your presentation was really clear and easy to follow. You effectively communicated the problem and I thought your analysis was definitely effective. I think it would be interesting to explore why the 0.5 distance had higher % than the 1 mile distance. Maybe doing a comparison of housing prices by distance from the supermarket would help tell that story?

**Comment by haonguyen318** [comment]
Hi Jessica! I really enjoyed your presentation! The topic that you chose to focus on for this project is very interesting and relevant to a large population in the U.S. Your code demonstration on R was very clear and I liked that you walked us step by step through how you generated your bar graph using ggplot. Your bar graph at the end was also very visually easy to understand and it clearly highlights the correlation between percent of low income population and the distance from the supermarkets.

**Comment by Deap-Bhandal** [comment]
The presentation was well organized and your analysis is clean and well-explained. The end plot does show the prevalence of food deserts in low income areas. I did have some questions about the dataset though. What definitions did the researchers assign to low-income (was below the poverty line a cut-off) and to supermarkets (was any type of retailer of produce counted)? I'm curious about the latter since not all retailers focus on healthy products.

**Comment by jessicadeanda** [comment]
> Great job @jessicadeanda, your presentation was really clear and easy to follow. You effectively communicated the problem and I thought your analysis was definitely effective. I think it would be interesting to explore why the 0.5 distance had higher % than the 1 mile distance. Maybe doing a comparison of housing prices by distance from the supermarket would help tell that story?

Thank you Robert! That was an interesting and unexpected result. I need to evaluate the statistical significance of these results and add error bars to the plot in order to see whether or not the difference between 0.5 and 1 miles is meaningful, but I do think it would be interesting to compare housing prices by distance if there is public data on that!

**Comment by jessicadeanda** [comment]
> Hi Jessica! I really enjoyed your presentation! The topic that you chose to focus on for this project is very interesting and relevant to a large population in the U.S. Your code demonstration on R was very clear and I liked that you walked us step by step through how you generated your bar graph using ggplot. Your bar graph at the end was also very visually easy to understand and it clearly highlights the correlation between percent of low income population and the distance from the supermarkets.

Thank you Hao!!

**Comment by jessicadeanda** [comment]
> The presentation was well organized and your analysis is clean and well-explained. The end plot does show the prevalence of food deserts in low income areas. I did have some questions about the dataset though. What definitions did the researchers assign to low-income (was below the poverty line a cut-off) and to supermarkets (was any type of retailer of produce counted)? I'm curious about the latter since not all retailers focus on healthy products.

Thank you Deap! According to the USDA, census tracts were flagged as low income if they met _any_ the following criteria:
1. The tract’s poverty rate was greater than 20%
2. The tract’s median family income was less than or equal to 80% of the State-wide median family income
3. The tract was in a metropolitan area and had a median family income less than or equal to 80% of the metropolitan area's median family income

There was no additional information about the supermarkets, but you bring up a good point. It is very likely that census tracts near supermarkets may still lack access to nutritional foods.

**Comment by soniavsd** [comment]
Jessica, I really enjoyed your presentation, especially how it pertains to the sustainable and social justice intersection of modern society. After watching your video and reading a bit of the book, "The Unbearable Whiteness of Milk" that you recommended to another commenter, I thought of a question: Why would a supermarket company refrain from placing one of their store in a food desert, if, economically it would flourish given that it is the only market available to most residents over a wide distance? May be a dumb question, but I just wanted to hear your take on it :)

**Comment by chausteven** [comment]
Hey Jessica, I thought your step-by-step explanation of your code made it really easy to follow! I really enjoyed your topic as it resonated with my own community back home. I noticed that in your dataset shown at the beginning that some counties had multiple entries and that each entry had different data. Why did each county have multiple entries with varying data? How did you separate or combine these data in order to analyze each population?

**Comment by jessicadeanda** [comment]
> Jessica, I really enjoyed your presentation, especially how it pertains to the sustainable and social justice intersection of modern society. After watching your video and reading a bit of the book, "The Unbearable Whiteness of Milk" that you recommended to another commenter, I thought of a question: Why would a supermarket company refrain from placing one of their store in a food desert, if, economically it would flourish given that it is the only market available to most residents over a wide distance? May be a dumb question, but I just wanted to hear your take on it :)

Thank you Sonia, I'm glad you read a bit of the book! That is actually a really good question. I couldn't find much information about why that is, but from what I read, it's not economically beneficial (sometimes even feasible) for supermarkets to open in food deserts. [AP News](https://apnews.com/36a15398c115484e8dc02ae62902e3e7/grocery-chains-leave-food-deserts-barren-ap-analysis-finds) reports that supermarkets struggle to stay in business because "a large customer base on food stamps creates erratic flows with a rush of business in the beginning of the month when food stamps are issued, but slow business at the end of the month. Insurance and security can be more costly in neighborhoods perceived to be high crime, and workers from neighborhoods with high unemployment sometimes need extra training for basic job skills."

**Comment by jessicadeanda** [comment]
> Jessica, I really enjoyed your presentation, especially how it pertains to the sustainable and social justice intersection of modern society. After watching your video and reading a bit of the book, "The Unbearable Whiteness of Milk" that you recommended to another commenter, I thought of a question: Why would a supermarket company refrain from placing one of their store in a food desert, if, economically it would flourish given that it is the only market available to most residents over a wide distance? May be a dumb question, but I just wanted to hear your take on it :)

Thank you Vanessa, I'm glad you read a bit of the book! That is actually a really good question. I couldn't find much information about why that is, but from what I read, it's not economically beneficial (sometimes even feasible) for supermarkets to open in food deserts. AP News reports that supermarkets struggle to stay in business because "a large customer base on food stamps creates erratic flows with a rush of business in the beginning of the month when food stamps are issued, but slow business at the end of the month. Insurance and security can be more costly in neighborhoods perceived to be high crime, and workers from neighborhoods with high unemployment sometimes need extra training for basic job skills."

**Comment by jessicadeanda** [comment]
> Hey Jessica, I thought your step-by-step explanation of your code made it really easy to follow! I really enjoyed your topic as it resonated with my own community back home. I noticed that in your dataset shown at the beginning that some counties had multiple entries and that each entry had different data. Why did each county have multiple entries with varying data? How did you separate or combine these data in order to analyze each population?

Thank you Steven, I'm glad you you found the topic meaningful! The data in my file was actually entered by census tract, which is a subdivision of a county. To combine these data, I just added all of the entries using the sum() function. This gave me the total population count per distance of the entire country, but now that you mention it, it probably would be a good ides to look at trends within individual counties (like LA county).
