### ISSUE TITLE
git commit fails, object file is empty

### ISSUE THREAD

**Issue by robertreny** [ShawnTylerSchwartz/eeb-c177-w20#8]
Hi @ShawnTylerSchwartz ,

I went to add to my food log using the same process I have been doing but I am now getting an error message. The code along with my origin code is below. I realized my week-one directory is not under lab-assignments. My edits to the food log are saved in the terminal, it is just the commit part that is failing.

`week-one$ git commit 
error: object file .git/objects/23/0b451271a47450014bb798d99942462108cdfe is empty
error: object file .git/objects/23/0b451271a47450014bb798d99942462108cdfe is empty
fatal: loose object 230b451271a47450014bb798d99942462108cdfe (stored in .git/objects/23/0b451271a47450014bb798d99942462108cdfe) is corrupt
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk/week-one$ git config --list --show-origin
file:/home/eebc177student/.gitconfig    user.name=robertreny
file:/home/eebc177student/.gitconfig    user.email=robertr@ucla.edu
file:/home/eebc177student/.gitconfig    credential.helper=cache --timeout=3600
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=true
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        remote.origin.url=https://github.com/robertreny/robertrenyhwk.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk/week-one$ 
`

**Comment by ShawnTylerSchwartz** [comment]
Duplicate of #

**Comment by shawntz** [comment]
Hi @robertreny, this error seems to be a duplicate of issue #5. Please check out the solution I posted there and see if it can solve your error. If not, then let me know so we can figure out another solution. [https://github.com/ShawnTylerSchwartz/eeb-c177-w20/issues/5](https://github.com/ShawnTylerSchwartz/eeb-c177-w20/issues/5).

**Comment by robertreny** [comment]
Hi @ShawnTylerSchwartz, I tried the solution and git commit worked but not the git push. The code is below and seems to be saying there is an issue with my branch order. 

(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk$ git status
error: object file .git/objects/23/0b451271a47450014bb798d99942462108cdfe is empty
error: object file .git/objects/23/0b451271a47450014bb798d99942462108cdfe is empty
fatal: loose object 230b451271a47450014bb798d99942462108cdfe (stored in .git/objects/23/0b451271a47450014bb798d99942462108cdfe) is corrupt
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk$ cp -a .git .git-old
fin(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyh find .git/objects/ -type f -empty | xargs rm
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk$ git fetch -p
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
git fsck --full
git status
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 27 (delta 4), reused 23 (delta 4), pack-reused 0
Unpacking objects: 100% (27/27), done.
From https://github.com/robertreny/robertrenyhwk
 * [new branch]      master     -> origin/master
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk$ git fsck --full
Checking object directories: 100% (256/256), done.
dangling blob 8c577bbac2cdcf41390bdc7d101316f05764b00e
dangling blob 248f2152cf64279321d85af4203ca26f7edcce5f
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   week-one/.food-log.txt.swp
	modified:   week-one/food-log.txt
	new file:   week-one/testestfile.txt

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    week-one/.food-log.txt.swp

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.git-old/

(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk$ ls
lab-excercises  week-one
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk$ cd week-one
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk/week-one$ ls
food-log.txt  testestfile.txt
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk/week-one$ nano food-log.txt
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk/week-one$ git add -A
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk/week-one$ git commit -m "retrying breakfast 1/12 after following issue #5 directions"
[master 26997f8] retrying breakfast 1/12 after following issue #5 directions
 52 files changed, 681 insertions(+)
 create mode 100644 .git-old/COMMIT_EDITMSG
 create mode 100644 .git-old/HEAD
 create mode 100644 .git-old/config
 create mode 100644 .git-old/description
 create mode 100755 .git-old/hooks/applypatch-msg.sample
 create mode 100755 .git-old/hooks/commit-msg.sample
 create mode 100755 .git-old/hooks/fsmonitor-watchman.sample
 create mode 100755 .git-old/hooks/post-update.sample
 create mode 100755 .git-old/hooks/pre-applypatch.sample
 create mode 100755 .git-old/hooks/pre-commit.sample
 create mode 100755 .git-old/hooks/pre-push.sample
 create mode 100755 .git-old/hooks/pre-rebase.sample
 create mode 100755 .git-old/hooks/pre-receive.sample
 create mode 100755 .git-old/hooks/prepare-commit-msg.sample
 create mode 100755 .git-old/hooks/update.sample
 create mode 100644 .git-old/index
 create mode 100644 .git-old/info/exclude
 create mode 100644 .git-old/logs/HEAD
 create mode 100644 .git-old/logs/refs/heads/master
 create mode 100644 .git-old/logs/refs/remotes/origin/master
 create mode 100644 .git-old/objects/05/f4f70b0c7dee2e854e4c43ebeae4005fe4cc81
 create mode 100644 .git-old/objects/08/6fcbf732b14a822f2c7e75f7e1a34e442b831a
 create mode 100644 .git-old/objects/13/aa8794ed350342a4c564e3db96ec9f1d08bd91
 create mode 100644 .git-old/objects/1a/8013b60cd94cbaa4921a9a06427a985273b724
 create mode 100644 .git-old/objects/23/0b451271a47450014bb798d99942462108cdfe
 create mode 100644 .git-old/objects/23/f4b1e2a9261684782bc491b8f01fb83dfddbe4
 create mode 100644 .git-old/objects/24/8f2152cf64279321d85af4203ca26f7edcce5f
 create mode 100644 .git-old/objects/25/600ab6c6ad69bf8f2de4c73e00c5f1c5aa68a8
 create mode 100644 .git-old/objects/26/7ffcc3ea863272321112fb77d6745300131b51
 create mode 100644 .git-old/objects/48/8c5e7799c06883e5d74fa5bcb9ac05c249bb75
 create mode 100644 .git-old/objects/4b/e649b16a34e6714caa9d1989dc5f4b8449ecbd
 create mode 100644 .git-old/objects/53/ad1e48efec74a78a9f51b1cedaf2b77deb5708
 create mode 100644 .git-old/objects/5c/f3f50bbc3ae072cac6083c05af4e5f2e9b51e4
 create mode 100644 .git-old/objects/87/51d56d4aff301b3c6032643098a45d8d197e15
 create mode 100644 .git-old/objects/8c/577bbac2cdcf41390bdc7d101316f05764b00e
 create mode 100644 .git-old/objects/96/c1248ec40fa8c00d7317e262491815e334f163
 create mode 100644 .git-old/objects/96/e10df063c783fc7ea8b7c297a4f45b2f298fdd
 create mode 100644 .git-old/objects/9a/8c297d58f8ea957212810dd0977f496ed40161
 create mode 100644 .git-old/objects/9b/3dff099c1c140199bda091e875d5fa016f7bf9
 create mode 100644 .git-old/objects/a7/3e88fd99a2f46cf888a7d9be7287b6fc1725d2
 create mode 100644 .git-old/objects/ae/8f7e4e3cff9fbdc5fb2bee97cf03d9c79406a6
 create mode 100644 .git-old/objects/b9/17ff5da660c8c3f72c227db354b8a1934e42f4
 create mode 100644 .git-old/objects/bb/07e760a1821e6614deb56592c60a2b1d7e5e9f
 create mode 100644 .git-old/objects/c0/4876309689b24206c76d16f13be06cb704533f
 create mode 100644 .git-old/objects/c6/79e554047d8e1c2d0b0984c55cace2b87c0f37
 create mode 100644 .git-old/objects/d8/448971153fa1b582b88f7aeb8be94f41b3986a
 create mode 100644 .git-old/objects/d8/feaedddc22c0c2ffc3d9c86818c1ce265f46d4
 create mode 100644 .git-old/objects/e6/6ebc5cdf99796add16d74850b637d6d5bb5a99
 create mode 100644 .git-old/refs/heads/master
 create mode 100644 .git-old/refs/remotes/origin/master
 create mode 100644 week-one/testestfile.txt
(base) eebc177student@eebc177student-VirtualBox:~/Developer/repos/robertrenyhwk/week-one$ git push origin master
Username for 'https://github.com': robertreny
Password for 'https://robertreny@github.com': 
To https://github.com/robertreny/robertrenyhwk.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/robertreny/robertrenyhwk.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by shawntz** [comment]
@robertreny it looks like the answer may be embedded at the bottom of the output you have attached:

> hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.

Try `git pull`, then `git push origin master`.

If this doesn’t work, paste the output here so we can see what to do next. If it works, let me know as well.

**Comment by robertreny** [comment]
@ShawnTylerSchwartz sorry I didn't include that, I tried the git pull but it didn't work without specifying the remote and branch. I'll try some things and let you know.

**Comment by shawntz** [comment]
@robertreny okay, no worries. Let me know if you’re able to troubleshoot this. Otherwise we can take a look tomorrow in lab.

**Comment by robertreny** [comment]
@ShawnTylerSchwartz It looks like it is fixed now! Thanks!
