### ISSUE TITLE
Moataz Basyouni - Lightning Presentation

### ISSUE THREAD

**Issue by motazb** [ShawnTylerSchwartz/eeb-c177-w20#80]
https://youtu.be/eZOcSXbEAKs

**Comment by LinhN16** [comment]
This was a really interesting dataset that you chose to analyze, Moataz! It is extremely interesting to break down the dataset into different trends that could be analyzed and it was especially intriguing to see the results of the correlation graph. I wonder how well this program did in terms of its original goals being to increase efficiency in hospitals.

**Comment by omerlavian20** [comment]
Great presentation and AWESOME project idea (I would imagine that this program could be **particularly** useful given the current world situation.).
I was wondering if you did any statistical analysis on your data to determine if any of the trends you noticed were statistically significant. If you haven't done this and would like ideas on how to do statistical analyses rather easily in Python, I would recommend looking into scipy.stats. It helped me tremendously in my project!

**Comment by alexphu1230** [comment]
Hi! I thought that the data set that you chose to analyze was super interesting, as I wouldn't think that these small injuries could hurt hospital efficiency. I thought it was also nice how you included your color coded visual! It really helped make the data understandable and it is very cool to see the work you put into your analysis!

**Comment by altaing** [comment]
Hello, I thought your dataset and project idea was really interesting and relevant! Do you know what year or years this data was collected? It might be really cool to be able to compare what type of injuries or when they occur change overtime. Were you able to determine if any of the differences between your values were significant or not?

**Comment by haonguyen318** [comment]
This is a great presentation Moataz! I like your code demonstration and how you explained each of your code and their purpose as well as what the data means. Your correlation matrix was also very easy to understand and it was nice to have a visual of what the data looks like on the matrix.

**Comment by motazb** [comment]
> This was a really interesting dataset that you chose to analyze, Moataz! It is extremely interesting to break down the dataset into different trends that could be analyzed and it was especially intriguing to see the results of the correlation graph. I wonder how well this program did in terms of its original goals being to increase efficiency in hospitals.

Thank you! I appreciate it.

**Comment by motazb** [comment]
> Great presentation and AWESOME project idea (I would imagine that this program could be **particularly** useful given the current world situation.).
> I was wondering if you did any statistical analysis on your data to determine if any of the trends you noticed were statistically significant. If you haven't done this and would like ideas on how to do statistical analyses rather easily in Python, I would recommend looking into scipy.stats. It helped me tremendously in my project!

I didn't do statistical tests on the trends but that would definitely be an awesome idea. Just looking at my correlation matrix though, I wasn't satisfied with what it showed because I felt like there should be more trends. I actually tried fixing this by manipulating how the data was grouped together using R, and it improve the analyzation of the trends. But, I would still expect to see more. I think with further adjustments to how the data is grouped, that correlation matrix should get more colorful, and some statistical tests for significance would be incredibly handy! Thank you!

**Comment by motazb** [comment]
> Hi! I thought that the data set that you chose to analyze was super interesting, as I wouldn't think that these small injuries could hurt hospital efficiency. I thought it was also nice how you included your color coded visual! It really helped make the data understandable and it is very cool to see the work you put into your analysis!

Thanks a lot! There are hundreds of thousands of each one of those injuries, so tracking their trends would certainly have an effect on the hospital's efficiency in using its resources. Every second can count.

**Comment by motazb** [comment]
> Hello, I thought your dataset and project idea was really interesting and relevant! Do you know what year or years this data was collected? It might be really cool to be able to compare what type of injuries or when they occur change overtime. Were you able to determine if any of the differences between your values were significant or not?

I do know what year, it's from 2015! You're right, it probably would be interesting to compare the types of injuries over time. There could be some trends in that definitely! I didn't determine if the trends were significant or not because I wanted to do some more adjusting to how it was grouped. I felt like it wasn't perfect yet. But testing for significance would for sure be the very next step to see which trends should really be observed and further studied. Thank you!

**Comment by motazb** [comment]
> This is a great presentation Moataz! I like your code demonstration and how you explained each of your code and their purpose as well as what the data means. Your correlation matrix was also very easy to understand and it was nice to have a visual of what the data looks like on the matrix.

I'm glad you liked it. Yes, the correlation matrix came out very clear and easy to read and I was glad it did. Thank you.

**Comment by soniavsd** [comment]
Wow! I really enjoyed your presentation! You had a very unique idea that was analyzed very thoroughly. Is there a way to determine if your findings on comparing treatments in the winter and summer are statistically significant? I think it would be much more enticing if that were the case to convince hospitals to shift resource usage!

**Comment by chausteven** [comment]
Hey Moataz, I thought the way you presented your code made it really easy to follow. I knew what exact data you were trying to extract using your code. Although your correlation matrix did really show any trends, I thought it was an excellent way to display possible trends for your dataset. What do you think those greenish-blue square, like in age/disposition,  might signify about the relationship between those two variables?

**Comment by goharmihranian** [comment]
Hi Moataz! Loved how you took such a complex, yet practical, dataset and used it to allow for an increase in the maximum efficiency of our healthcare system. Figuring out when people get injured the most is a great piece of information for hospitals, as it will allow them to be more well prepared. Awesome work!
