### ISSUE TITLE
Vanessa Ramos- Lightning Presentation

### ISSUE THREAD

**Issue by soniavsd** [ShawnTylerSchwartz/eeb-c177-w20#81]
https://youtu.be/vnpF2FiMnU8

**Comment by haonguyen318** [comment]
This is a great video with easy to follow demonstrations of the code. I also like your explanation of EPI and how you showed the correlation between EPI and factors that affects it using your plots. You also did a great job of explaining what a K means cluster plot is and how you used it to show the four income brackets. I think it would be clearer if you were to label the x and y axes for all of the plots.

**Comment by omerlavian20** [comment]
Great presentation and awesome topic! If I read correctly you said you plotted the k-means cluster results in R. Do you do that by performing the clustering within R, or is there a way of moving the points on the Python plot and plotting them in R?

**Comment by jessicadeanda** [comment]
Great analysis! The clusters are easy to discern given the color scheme. Like Hao suggested, I think adding a title to both axes is necessary for easy interpretation, but other than that, the plot is clear.

**Comment by fridalejandra** [comment]
Hi Vanessa, very nice topic! I'm glad to see you used the k-means cluster plot for your data. For the first plot it appears to be in 'ggplot' and you have a positive correlation happening, would you be running other tests to validate and further explore this relationship?

**Comment by WhitneyTsaiNakashima** [comment]
Well done! Your presentation was really clear, easy to follow, and an interesting topic. Comparing your scatter plot and the k-means clustering, it appears that there is some variation in the results of the clustering algorithm and the income categorization. Did you explore this relationship further?

**Comment by soniavsd** [comment]
> This is a great video with easy to follow demonstrations of the code. I also like your explanation of EPI and how you showed the correlation between EPI and factors that affects it using your plots. You also did a great job of explaining what a K means cluster plot is and how you used it to show the four income brackets. I think it would be clearer if you were to label the x and y axes for all of the plots.

Thank you! I know, working with the data all this time it became second nature to understand what the graph meant and what its variables were, so I forgot that others wouldn't know forgot to add axes! My fault but it is definitely something to remember for next time :)

**Comment by soniavsd** [comment]
> Great presentation and awesome topic! If I read correctly you said you plotted the k-means cluster results in R. Do you do that by performing the clustering within R, or is there a way of moving the points on the Python plot and plotting them in R?


sorry I should have been a bit more clear- I created the k means cluster plots in python, and the scatter plots in R. To be honest, I didn't even think of the possibility of running a k means cluster plot in R, great question!

**Comment by soniavsd** [comment]
> Well done! Your presentation was really clear, easy to follow, and an interesting topic. Comparing your scatter plot and the k-means clustering, it appears that there is some variation in the results of the clustering algorithm and the income categorization. Did you explore this relationship further?

Thank you! Yes I definitely noticed that, I was motivated by Shawn to use ggrepel to determine which countries are in which clusters so I'll keep you updated!

**Comment by motazb** [comment]
Hey Vanessa! Awesome job with your project! I think you chose a very interesting data set. I find it very odd though that higher-income locations correlated with better environmental health. I would guess higher-income locations have more factories and a higher percentage of people have cars and are very wasteful, while poorer locations wouldn't have the availability to the means which destroy the health of the environment. Anyways, this was definitely a great idea of a data set and very interesting results!

**Comment by Deap-Bhandal** [comment]
Great work on your project! Your analysis on income and EPI was clear and showed a strong correlation. I understand you focused on income and EPI, but at the beginning you also mentioned EPI's relationship with location. Did that also show any correlation? I could guess that it may not be as strong since there is a lot of variance between countries in a large area. Also, did you divide the countries based on location based on how the dataset did them or did you divide them afterwards?

**Comment by soniavsd** [comment]
> Great work on your project! Your analysis on income and EPI was clear and showed a strong correlation. I understand you focused on income and EPI, but at the beginning you also mentioned EPI's relationship with location. Did that also show any correlation? I could guess that it may not be as strong since there is a lot of variance between countries in a large area. Also, did you divide the countries based on location based on how the dataset did them or did you divide them afterwards?

Thank you! Yes I also tested the relationship between EPI and location along with environmental health and location/income, and ecosystem vitality and location/income. In general, it seems that Europe/European Union leads in sustainability, with other locations varying after. In order to determine which country goes into each location type, I used a government data base after I got the raw data!

**Comment by goharmihranian** [comment]
Hi Vanessa! I thought it was really cool that you incorporated what we had learned in class not too long ago about k-means into your final project. Awesome presentation overall, You really broke down your project and made it easily understandable for the rest of us.
