### ISSUE TITLE
Responding to lightning presentation posts

### ISSUE THREAD

**Issue by Deap-Bhandal** [ShawnTylerSchwartz/eeb-c177-w20#82]
@ShawnTylerSchwartz Are we assigned who we are supposed to respond to (if so where can I find the names) or do we decide who to respond to?

**Comment by shawntz** [comment]
@Deap-Bhandal sorry for the delay -- I'm about to post it on CCLE shortly. Things have been delayed and busy with everything going on and all the news unfolding rapidly. I will reply and send an email out on CCLE in a bit. Thank you for your patience

**Comment by Deap-Bhandal** [comment]
No worries! Thank you for the update.

**Comment by shawntz** [comment]
@Deap-Bhandal it has been posted on CCLE
