### ISSUE TITLE
Robert Reny's Lightning Presentation

### ISSUE THREAD

**Issue by robertreny** [ShawnTylerSchwartz/eeb-c177-w20#83]
https://www.youtube.com/watch?v=fzTbaLCjeCI

**Comment by KaranSingh-14** [comment]
Hey great presentation! I was wondering how were you able to get that animation to work. I am sorry, I just had a tough time hearing some parts of it. So did you use R and what exact component of ggplot or tidyverse did you use for the animation?

**Comment by jessicadeanda** [comment]
Great data visualization, displaying your data on a map makes it a lot easier to interpret! Before watching this presentation, I was actually wondering if latitude/longitude information was necessary to plot a map, so thank you for answering that! I think your presentation would be easier to follow if you show us your code, but your project looks really good.

**Comment by robertreny** [comment]
> Hey great presentation! I was wondering how were you able to get that animation to work. I am sorry, I just had a tough time hearing some parts of it. So did you use R and what exact component of ggplot or tidyverse did you use for the animation?

Hi @KaranSingh-14 sorry the sound wasn't great. Getting the animation to work was a real pain. First to get the basemap as I called it I used ggmap but to actually utilize ggmap you have to do a bunch of  pre-steps that I tried to list out in the last page of the presentation here: https://github.com/robertreny/eeb-c177-project/blob/master/Reny%20EEB%20Presentation.pdf

Once you do this you can call the map using a lat/long. To actually map the points I used ggplot2's geom_point. Then to animate this over the given timestamp I used gganimate's transition_time() function. It was a whole other thing to get the animation to work in the presentation but those are the steps for the gif!

**Comment by robertreny** [comment]
> Great data visualization, displaying your data on a map makes it a lot easier to interpret! Before watching this presentation, I was actually wondering if latitude/longitude information was necessary to plot a map, so thank you for answering that! I think your presentation would be easier to follow if you show us your code, but your project looks really good.

Thank you @jessicadeanda ! If you are interested in doing a lat/long map in the same way in the future it was a bit of a pain but I responded to Karan describing the steps.

**Comment by haonguyen318** [comment]
Hi Robert! I enjoyed your explanation of your code and how you created your graphs. It was very thorough and informative. It would be better if you could have added screenshots of your code or did a screenrecording of your code demonstration so that it's easier for the audience to visualize. other than that I really enjoyed your findings base on your data analysis.

**Comment by shreyatrivedi26** [comment]
A very good visualization Robert! 
The animated graph actually illustrate very well what you intended to show. I think I would have followed it even better with the codes displayed/demonstrated and the audio bit clearer. 
I understand that the pre-processing of data has been done in Python and the visualization obtained in R, I was just curious what was your data type? What is .tiff? 
Since you used pandas I am assuming it is .csv? But then did you use the basemap in Python or in R? Since I also work with plotting maps, it would be great to know which basemap works better and is more visually appealing. 

Also, the animation would have been clearer with an additional legend attached to it. I believe if you added a legend with different sizes of circle, it would reflect the heat effect better. 

But yes, you did a really good job!

**Comment by LinhN16** [comment]
Aside from technical aspects that others have commented on, this is a super cool demonstration of code! Even without seeing the code, I was able to follow along with your thinking process / how you got to creating the graphs. The animation aspect of your data analysis made your presentation 10x cooler, super creative idea!

**Comment by Deap-Bhandal** [comment]
The animation at the end was really impressive! I understand you needed the latitude and longitude coordinates for the graph and I heard you say that you inputted the coordinates later. Was this done manually by searching for the coordinates for each location column and adding the coordinates in new columns or were you able to find a more efficient way to do this?

**Comment by robertreny** [comment]
> Hi Robert! I enjoyed your explanation of your code and how you created your graphs. It was very thorough and informative. It would be better if you could have added screenshots of your code or did a screenrecording of your code demonstration so that it's easier for the audience to visualize. other than that I really enjoyed your findings base on your data analysis.

Thank you @haonguyen318 ! I will definitely include more code demonstration in the future.

**Comment by robertreny** [comment]
> A very good visualization Robert!
> The animated graph actually illustrate very well what you intended to show. I think I would have followed it even better with the codes displayed/demonstrated and the audio bit clearer.
> I understand that the pre-processing of data has been done in Python and the visualization obtained in R, I was just curious what was your data type? What is .tiff?
> Since you used pandas I am assuming it is .csv? But then did you use the basemap in Python or in R? Since I also work with plotting maps, it would be great to know which basemap works better and is more visually appealing.
> 
> Also, the animation would have been clearer with an additional legend attached to it. I believe if you added a legend with different sizes of circle, it would reflect the heat effect better.
> 
> But yes, you did a really good job!

Thank you for the feedback @shreyatrivedi26 !My data was just csv files in notepad. The basemap was loaded in directly to R using ggmap (so no downloading from a file) and it is a google map image but I am not sure the file type. When I plotted over it it was exported as a gif.

**Comment by robertreny** [comment]
> Aside from technical aspects that others have commented on, this is a super cool demonstration of code! Even without seeing the code, I was able to follow along with your thinking process / how you got to creating the graphs. The animation aspect of your data analysis made your presentation 10x cooler, super creative idea!

Thank you @LinhN16 ! I appreciate the feedback and that you enjoyed the animation!

**Comment by robertreny** [comment]
> The animation at the end was really impressive! I understand you needed the latitude and longitude coordinates for the graph and I heard you say that you inputted the coordinates later. Was this done manually by searching for the coordinates for each location column and adding the coordinates in new columns or were you able to find a more efficient way to do this?

Thank you @Deap-Bhandal ! Yeah so that probably got lost due to the poor audio. I added the lat/long using python. First I created two functions (set_long and set_lat) that would return the appropriate lat/long corresponding to each station ID . I then used the assign function to apply the set_long and set_lat functions to each row of the dataframe. Let me know if that makes sense... my code is here: https://github.com/robertreny/eeb-c177-project/blob/master/analyses/Data%20for%20mapping.ipynb

**Comment by goharmihranian** [comment]
Hi Robert! I like the non-traditional approach to verbally explain your code compared to just showing us. It makes us think a little bit harder and visualize it. I really liked the animation of the plot you came up with; must have taken a lot of patience!
