### ISSUE TITLE
Homework Clarification and Virtualbox Update

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#9]
I've got two questions: 
1.) Is the homework for tomorrow just the "Working with Files and Directories" thing or do we also have to do the whole tutorial?

2.) I got a notification today about updating Virtualbox. Should we do that or should we stay with the version we downloaded at the start of the quarter?

Thanks in advance!

**Comment by goharmihranian** [comment]
I believe we do the whole tutorial, as I don't see any specification on a certain part.

**Comment by shawntz** [comment]
@omerlavian20 @goharmihranian is correct, you do the entire tutorial. 

To answer your second question, let’s not update it to avoid any potential issues that may arise 👍

**Comment by omerlavian20** [comment]
Sorry to ask another question, but @ShawnTylerSchwartz if you don't mind my asking, since you posted the link to the third part as opposed to the beginning of the tutorial, do we finish the tutorial from there, or do we start from the beginning of the whole thing? Again I'm very sorry that I'm continuing to ask questions. I just got confused since the link was for third part of the tutorial.
